# Nodes
## Location node
- Frequency of a location is visited by a patient, _Fl_
- Total duration of patient stayed in a location, _Dp (s)_
- Number of susceptible humans, _Sl_

$\sum{\textrm{Location node parameter}_i} = (Fl_i + Dp_i + Sl_i ) $

## Human node 
- Frequency of human visited a location, _Fh_
- Total duration of human stayed in a location, _Du (s)_
- Vaccination, _V_
- Age of the susceptible human, _As_
- Pregnancy, _P_

$\sum{\textrm{Human node parameter}_j} = (Fh_{j,i} + Du_{j,i} + V_j + As_j+P_j), i \in \textrm{Locations}$

## Link weight
$MCS_{i,j} = \sum{\textrm{Human node parameter}_j} + \sum{\textrm{Location node parameter}_i}= (Fh_{j,i} + Du_{j,i} + V_j + As_j+P_j ) + (Fl_i + Dp_i + Sl_i )$

# Raw data
## Location data
All valid locations visited by (1) patient, (2) susceptible human

In [1]:
location<-read.csv('location.csv')
names(location)<-c('Location.Address', 'Latitude', 'Longitude', 'Population')
location

   Location.Address                                         Latitude Longitude
1  Kampung Felcra Bukit Kapah,21700 Kula Berang, Terengganu 5.107582 102.9058
2  Kampung Tengkawang,21700 Kuala Berang, Terengganu        5.162444 102.9279
3  Kampung Gaung,21700 Kuala Berang, Terengganu             5.070730 102.9988
4  Kampung Tajin,21700 Kuala Berang, Terengganu             5.118371 102.9894
5  Kampung Chapu,21700 Kuala Berang, Terengganu             5.178144 102.8967
6  Kampung Bukit Kubur,21700 Kuala Berang, Terengganu       5.222297 102.8724
7  Kampung Teris,21700 Kuala Berang, Terengganu             5.216057 102.8752
8  Kampung Gapur,21700 Kuala Berang, Terengganu             5.187075 102.8881
9  Kampung Paya Akob,21700 Kuala Berang, Terengganu         5.124478 102.9849
10 Kampung Kuala Ping,21700 Kuala Berang, Terengganu        5.159361 102.9067
11 Kampung Kepah,21700 Kuala Berang, Terengganu             5.149787 102.9376
12 Kampung Telaga,21700 Kuala Berang Terengganu             5.092681 102.9994
13 Kampung Butut,21700 Kuala Berang, Terengganu             5.084796 103.0111
14 Kampung Katak,21700 Kuala Berang, Terengganu             5.158758 102.9002
15 Kampung Langgar,21700 Kuala Berang, Terengganu           5.102350 103.0104
16 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu      5.173624 102.8980
   Population
1  1200
2  1300
3  1400
4  1250
5  1350
6  1240
7  1350
8  1360
9  1400
10 1430
11 1450
12 2000
13 1100
14 1150
15 1900
16 1750

In [2]:
#processLocation <- function(raw_location){
#    library(geosphere)
#    return(data.frame(distm(raw_location[,c('Longitude','Latitude')],fun = distVincentyEllipsoid)))
#}

In [3]:
#processedLocation<-processLocation(location)
#processedLocation

In [4]:
locationMarker<-data.frame(paste("X", 1:nrow(location),sep=''),location[,'Location.Address'])
names(locationMarker)<-c('marker', 'Location.Address')
locationMarker

   marker Location.Address
1  X1     Kampung Felcra Bukit Kapah,21700 Kula Berang, Terengganu
2  X2     Kampung Tengkawang,21700 Kuala Berang, Terengganu
3  X3     Kampung Gaung,21700 Kuala Berang, Terengganu
4  X4     Kampung Tajin,21700 Kuala Berang, Terengganu
5  X5     Kampung Chapu,21700 Kuala Berang, Terengganu
6  X6     Kampung Bukit Kubur,21700 Kuala Berang, Terengganu
7  X7     Kampung Teris,21700 Kuala Berang, Terengganu
8  X8     Kampung Gapur,21700 Kuala Berang, Terengganu
9  X9     Kampung Paya Akob,21700 Kuala Berang, Terengganu
10 X10    Kampung Kuala Ping,21700 Kuala Berang, Terengganu
11 X11    Kampung Kepah,21700 Kuala Berang, Terengganu
12 X12    Kampung Telaga,21700 Kuala Berang Terengganu
13 X13    Kampung Butut,21700 Kuala Berang, Terengganu
14 X14    Kampung Katak,21700 Kuala Berang, Terengganu
15 X15    Kampung Langgar,21700 Kuala Berang, Terengganu
16 X16    Kampung Pasir Simpul,21700 Kuala Berang, Terengganu

## Patient Data & Human Data
Patient & location that they have visited

**KIV** _sample_

| Patient/Human | Location | Visit_Frequency | Visit_Duration(s) |
|:-|:-|:-|:-|
|Patient1|Kampung Pasir Simpul,21700 Kuala Berang, Terengganu|3|28800|
|Patient2|Kampung Pasir Simpul,21700 Kuala Berang, Terengganu|1|18800|
|Human1|Kampung Pasir Simpul,21700 Kuala Berang, Terengganu|1|18800|
|Human2|Kampung Pasir Simpul,21700 Kuala Berang, Terengganu|1|18800|
.....

In [5]:
patient<-read.csv('patient.csv')
names(patient)<-c('Patient', 'Location', 'Visit_Frequency', 'Visit_Duration.s.')
patient
patientM<-merge(patient, locationMarker, by.x='Location', by.y='Location.Address')
patientM

  Patient  Location                                            Visit_Frequency
1 Patient1 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu 3
2 Patient2 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu 1
3 Patient2 Kampung Teris,21700 Kuala Berang, Terengganu        2
4 Patient3 Kampung Paya Akob,21700 Kuala Berang, Terengganu    1
5 Patient4 Kampung Katak,21700 Kuala Berang, Terengganu        1
  Visit_Duration.s.
1 28800
2 18800
3 20123
4 12500
5 10230

  Location                                            Patient  Visit_Frequency
1 Kampung Katak,21700 Kuala Berang, Terengganu        Patient4 1
2 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu Patient1 3
3 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu Patient2 1
4 Kampung Paya Akob,21700 Kuala Berang, Terengganu    Patient3 1
5 Kampung Teris,21700 Kuala Berang, Terengganu        Patient2 2
  Visit_Duration.s. marker
1 10230             X14
2 28800             X16
3 18800             X16
4 12500             X9
5 20123             X7

## Human data

In [6]:
human<-read.csv('human2.csv')
human
names(human)<-c('Human', 'Location', 'Visit_Frequency', 'Visit_Duration.s.', 'Vaccination', 'Age', 'Pregnancy')
humanM<-merge(human, locationMarker, by.x='Location', by.y='Location.Address')
humanM

   Human  Location
1  Human1 Kampung Felcra Bukit Kapah,21700 Kula Berang, Terengganu
2  Human1 Kampung Butut,21700 Kuala Berang, Terengganu
3  Human2 Kampung Kepah,21700 Kuala Berang, Terengganu
4  Human3 Kampung Gaung,21700 Kuala Berang, Terengganu
5  Human4 Kampung Teris,21700 Kuala Berang, Terengganu
6  Human4 Kampung Gapur,21700 Kuala Berang, Terengganu
7  Human4 Kampung Telaga,21700 Kuala Berang Terengganu
8  Human5 Kampung Tajin,21700 Kuala Berang, Terengganu
9  Human5 Kampung Paya Akob,21700 Kuala Berang, Terengganu
10 Human5 Kampung Langgar,21700 Kuala Berang, Terengganu
11 Human6 Kampung Chapu,21700 Kuala Berang, Terengganu
12 Human6 Kampung Kuala Ping,21700 Kuala Berang, Terengganu
13 Human7 Kampung Bukit Kubur,21700 Kuala Berang, Terengganu
14 Human7 Kampung Katak,21700 Kuala Berang, Terengganu
15 Human8 Kampung Tengkawang,21700 Kuala Berang, Terengganu
16 Human8 Kampung Teris,21700 Kuala Berang, Terengganu
17 Human8 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu
   Visit_Frequency Visit_Duration.s. Vaccination Age Pregnancy
1  1               28800             0           23  1
2  1               18800             1           45  0
3  2               20123             0           54  0
4  1               12500             1           65  0
5  1               10230             1           12  0
6  2               21600             2           15  0
7  1               12600             2           37  1
8  3               37800             2           73  0
9  1               14400             1           29  1
10 1                9000             2            8  0
11 1               10800             1           14  0
12 3               21600             1           33  1
13 2               25200             1           65  0
14 1               13320             0           55  0
15 1               22680             0           78  0
16 2               18000             0           27  1
17 1               27000             0            1  0

   Location                                                 Human
1  Kampung Bukit Kubur,21700 Kuala Berang, Terengganu       Human7
2  Kampung Butut,21700 Kuala Berang, Terengganu             Human1
3  Kampung Chapu,21700 Kuala Berang, Terengganu             Human6
4  Kampung Felcra Bukit Kapah,21700 Kula Berang, Terengganu Human1
5  Kampung Gapur,21700 Kuala Berang, Terengganu             Human4
6  Kampung Gaung,21700 Kuala Berang, Terengganu             Human3
7  Kampung Katak,21700 Kuala Berang, Terengganu             Human7
8  Kampung Kepah,21700 Kuala Berang, Terengganu             Human2
9  Kampung Kuala Ping,21700 Kuala Berang, Terengganu        Human6
10 Kampung Langgar,21700 Kuala Berang, Terengganu           Human5
11 Kampung Pasir Simpul,21700 Kuala Berang, Terengganu      Human8
12 Kampung Paya Akob,21700 Kuala Berang, Terengganu         Human5
13 Kampung Tajin,21700 Kuala Berang, Terengganu             Human5
14 Kampung Telaga,21700 Kuala Berang Terengganu             Human4
15 Kampung Tengkawang,21700 Kuala Berang, Terengganu        Human8
16 Kampung Teris,21700 Kuala Berang, Terengganu             Human4
17 Kampung Teris,21700 Kuala Berang, Terengganu             Human8
   Visit_Frequency Visit_Duration.s. Vaccination Age Pregnancy marker
1  2               25200             1           65  0         X6
2  1               18800             1           45  0         X13
3  1               10800             1           14  0         X5
4  1               28800             0           23  1         X1
5  2               21600             2           15  0         X8
6  1               12500             1           65  0         X3
7  1               13320             0           55  0         X14
8  2               20123             0           54  0         X11
9  3               21600             1           33  1         X10
10 1                9000             2            8  0         X15
11 1               27000             0            1  0         X16
12 1               14400             1           29  1         X9
13 3               37800             2           73  0         X4
14 1               12600             2           37  1         X12
15 1               22680             0           78  0         X2
16 1               10230             1           12  0         X7
17 2               18000             0           27  1         X7

# Location Node 

## Link Matrix generation

$ LinkMatrix_{BMC network} (X_iH_j) = \{1,  \textrm{if }H_j\textrm{ visited }X_i; 0, \textrm{if }H_j\textrm{ did not visit} X_i $

In [7]:
generateLinkMatrix<-function(locations, Data, type){
    n_location = length(unique(locations[,'marker']))
    if (toupper(type) == "H"){
        n_dat = length(unique(Data[,'Human']))
    }else{
        n_dat = length(unique(Data[,'Patient']))
    }
    dm = matrix(ncol=n_dat, nrow=n_location)
    for (i in 1:nrow(Data)) {
        if (toupper(type) == "H"){
            pat = as.numeric(unlist(strsplit(as.character(Data[i,'Human']),'Human'))[[2]])
        }else{
            pat = as.numeric(unlist(strsplit(as.character(Data[i,'Patient']),'Patient'))[[2]])
        }
        loc = as.numeric(unlist(strsplit(as.character(Data[i,'marker']),'X'))[[2]])
        dm[loc,pat] = 1
    }
    result = as.data.frame(dm)
    result[is.na(result)] = 0
    row.names(result) <- c(paste("L",1:nrow(result), sep=''))
    names(result) <- c(paste(type,1:length(names(result)), sep=''))
    return(result)
}

In [8]:
lnkMtrx <- generateLinkMatrix(locationMarker, patientM, "P")
lnkMtrx

    P1 P2 P3 P4
L1  0  0  0  0
L2  0  0  0  0
L3  0  0  0  0
L4  0  0  0  0
L5  0  0  0  0
L6  0  0  0  0
L7  0  1  0  0
L8  0  0  0  0
L9  0  0  1  0
L10 0  0  0  0
L11 0  0  0  0
L12 0  0  0  0
L13 0  0  0  0
L14 0  0  0  1
L15 0  0  0  0
L16 1  1  0  0

## FL calculation
$Fl_i = \sum_{j=1}^{n\_patient} {\textrm{Link Matrix}_{BMC network} (X_jP_i) \times Fl_{i,j}}, i \in location, j \in patient$

In [9]:
generateFL<-function(locations, patientData, type, vector){
    if (toupper(type)=='P'){
        ty = 'Patient'
    }else{
        ty = 'Human'
    }
    n_location = length(unique(locations[,'marker']))
    n_patient = length(unique(patientData[,ty]))
    dm = matrix(ncol=n_patient, nrow=n_location)
    for (i in 1:nrow(patientData)) {
        pat = as.numeric(unlist(strsplit(as.character(patientData[i,ty]),ty))[[2]])
        loc = as.numeric(unlist(strsplit(as.character(patientData[i,'marker']),'X'))[[2]])
        dm[loc,pat] = as.numeric(patientData[i,'Visit_Frequency'])
    }
    result = as.data.frame(dm)
    result[is.na(result)] = 0
    if(vector == TRUE){
        FLVector = rowSums(result)
        return(FLVector)
    }else{
        row.names(result) <- c(paste("L",1:nrow(result), sep=''))
        names(result) <- c(paste(toupper(type),1:length(names(result)), sep=''))
        return(result)
    }
}

In [10]:
FL <- generateFL(locationMarker, patientM, 'p', TRUE)
FL

 [1] 0 0 0 0 0 0 2 0 1 0 0 0 0 1 0 4

## DP calculation
$DP_i = \sum_{j=1}^{n\_patient} {\textrm{Duration}_{i,j}}, i \in location, j \in patient$

In [11]:
generateDP <- function(locations, patientData){
    n_location = length(unique(locations[,'marker']))
    dm = matrix(ncol=1, nrow=n_location, data=0)
    for (i in 1:nrow(patientData)) {
        loc = as.numeric(unlist(strsplit(as.character(patientData[i,'marker']),'X'))[[2]])
        dm[loc,1] = dm[loc,1] + patientData[i, 'Visit_Duration.s.']
    }
    return(as.vector(dm))
}

In [12]:
DP <- generateDP(locationMarker, patientM)
class(DP)

[1] "numeric"

## SL calculation

In [13]:
generateSL <- function(locationMarker, locationData){
    temp <- merge(locationMarker, locationData, by.x='Location.Address', by.y='Location.Address')
    vals <- as.numeric(gsub("X","", temp$marker))
    temp<-temp[order(vals),]
    return(as.vector(temp$Population))
}

In [14]:
SL <- generateSL(locationMarker, location)
SL

 [1] 1200 1300 1400 1250 1350 1240 1350 1360 1400 1430 1450 2000 1100 1150 1900
[16] 1750

In [15]:
generateLocationNodeParameters <- function(locations, FL, DP, SL){
    temp = FL + DP + SL 
    locations['nodeParameter'] <- temp
    return(locations)
}

In [16]:
generateLocationNodeParameters(locationMarker, FL, DP, SL)

   marker Location.Address
1  X1     Kampung Felcra Bukit Kapah,21700 Kula Berang, Terengganu
2  X2     Kampung Tengkawang,21700 Kuala Berang, Terengganu
3  X3     Kampung Gaung,21700 Kuala Berang, Terengganu
4  X4     Kampung Tajin,21700 Kuala Berang, Terengganu
5  X5     Kampung Chapu,21700 Kuala Berang, Terengganu
6  X6     Kampung Bukit Kubur,21700 Kuala Berang, Terengganu
7  X7     Kampung Teris,21700 Kuala Berang, Terengganu
8  X8     Kampung Gapur,21700 Kuala Berang, Terengganu
9  X9     Kampung Paya Akob,21700 Kuala Berang, Terengganu
10 X10    Kampung Kuala Ping,21700 Kuala Berang, Terengganu
11 X11    Kampung Kepah,21700 Kuala Berang, Terengganu
12 X12    Kampung Telaga,21700 Kuala Berang Terengganu
13 X13    Kampung Butut,21700 Kuala Berang, Terengganu
14 X14    Kampung Katak,21700 Kuala Berang, Terengganu
15 X15    Kampung Langgar,21700 Kuala Berang, Terengganu
16 X16    Kampung Pasir Simpul,21700 Kuala Berang, Terengganu
   nodeParameter
1   1200
2   1300
3   1400
4   1250
5   1350
6   1240
7  21475
8   1360
9  13901
10  1430
11  1450
12  2000
13  1100
14 11381
15  1900
16 49354

# Human Node
## DU calculation

In [17]:
generateDU <- function (locations, humanData){
    n_location = length(unique(locations[,'marker']))
    n_humans = length(unique(humanData[,'Human']))
    dm = matrix(ncol=n_location, nrow=n_humans, data=0)
    for (i in 1:nrow(humanData)) {
        loc = as.numeric(unlist(strsplit(as.character(humanData[i,'marker']),'X'))[[2]])
        hum = as.numeric(unlist(strsplit(as.character(humanData[i,'Human']),'Human'))[[2]])
        dm[hum,loc] = dm[hum,loc] + humanData[i, 'Visit_Duration.s.']
    }
    res <- as.data.frame(dm)
    row.names(res) <- c(paste("H",1:nrow(res), sep=''))
    names(res) <- c(paste("L",1:length(names(res)), sep=''))
    return(res)
}

In [18]:
DU <- generateDU(locationMarker, humanM)
DU

   L1    L2    L3    L4    L5    L6    L7    L8    L9    L10   L11   L12
H1 28800     0     0     0     0     0     0     0     0     0     0     0
H2     0     0     0     0     0     0     0     0     0     0 20123     0
H3     0     0 12500     0     0     0     0     0     0     0     0     0
H4     0     0     0     0     0     0 10230 21600     0     0     0 12600
H5     0     0     0 37800     0     0     0     0 14400     0     0     0
H6     0     0     0     0 10800     0     0     0     0 21600     0     0
H7     0     0     0     0     0 25200     0     0     0     0     0     0
H8     0 22680     0     0     0     0 18000     0     0     0     0     0
   L13   L14   L15  L16
H1 18800     0    0     0
H2     0     0    0     0
H3     0     0    0     0
H4     0     0    0     0
H5     0     0 9000     0
H6     0     0    0     0
H7     0 13320    0     0
H8     0     0    0 27000

## Fh Calculation

In [19]:
lnkMtrxH <- generateLinkMatrix(locationMarker, humanM, "H")
lnkMtrxH

    H1 H2 H3 H4 H5 H6 H7 H8
L1  1  0  0  0  0  0  0  0
L2  0  0  0  0  0  0  0  1
L3  0  0  1  0  0  0  0  0
L4  0  0  0  0  1  0  0  0
L5  0  0  0  0  0  1  0  0
L6  0  0  0  0  0  0  1  0
L7  0  0  0  1  0  0  0  1
L8  0  0  0  1  0  0  0  0
L9  0  0  0  0  1  0  0  0
L10 0  0  0  0  0  1  0  0
L11 0  1  0  0  0  0  0  0
L12 0  0  0  1  0  0  0  0
L13 1  0  0  0  0  0  0  0
L14 0  0  0  0  0  0  1  0
L15 0  0  0  0  1  0  0  0
L16 0  0  0  0  0  0  0  1

In [20]:
FH <- generateFL(locationMarker, humanM, 'h', TRUE)
FH

 [1] 1 1 1 3 1 2 3 2 1 3 2 1 1 1 1 1

In [21]:
FHM <- t(generateFL(locationMarker, humanM, 'h', FALSE))
FHM

   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1 1  0  0  0  0  0  0  0  0  0   0   0   1   0   0   0
H2 0  0  0  0  0  0  0  0  0  0   2   0   0   0   0   0
H3 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0
H4 0  0  0  0  0  0  1  2  0  0   0   1   0   0   0   0
H5 0  0  0  3  0  0  0  0  1  0   0   0   0   0   1   0
H6 0  0  0  0  1  0  0  0  0  3   0   0   0   0   0   0
H7 0  0  0  0  0  2  0  0  0  0   0   0   0   1   0   0
H8 0  1  0  0  0  0  2  0  0  0   0   0   0   0   0   1

## V

In [22]:
generateVp <- function(locations, humanData){
    n_humans = length(unique(humanData[,'Human']))
    n_location = length(unique(locations[,'marker']))
    dm = matrix(ncol=n_location, nrow=n_humans, data=0)
    for (i in 1:nrow(humanData)) {
        vac = humanData[i, 'Vaccination']
        if(vac>=2){
            vacResult=0
        }else if (vac>0){
            vacResult=1
        }else{
            vacResult=2
        }
        hum = as.numeric(unlist(strsplit(as.character(humanData[i,"Human"]),"Human"))[[2]])
        loc = as.numeric(unlist(strsplit(as.character(humanData[i,'marker']),'X'))[[2]])
        dm[hum, loc] = vacResult
    }
    result <- as.data.frame(dm)
    row.names(result) <- c(paste("H",1:nrow(result), sep=''))
    names(result) <- c(paste("L",1:length(names(result)), sep=''))
    return(result)
}

In [23]:
Vp <- generateVp(locationMarker, humanM)
Vp

   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1 2  0  0  0  0  0  0  0  0  0   0   0   1   0   0   0
H2 0  0  0  0  0  0  0  0  0  0   2   0   0   0   0   0
H3 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0
H4 0  0  0  0  0  0  1  0  0  0   0   0   0   0   0   0
H5 0  0  0  0  0  0  0  0  1  0   0   0   0   0   0   0
H6 0  0  0  0  1  0  0  0  0  1   0   0   0   0   0   0
H7 0  0  0  0  0  1  0  0  0  0   0   0   0   2   0   0
H8 0  2  0  0  0  0  2  0  0  0   0   0   0   0   0   2

## As

In [24]:
generateAs <- function(locations, humanData){
    n_humans = length(unique(humanData[,'Human']))
    n_location = length(unique(locations[,'marker']))
    dm = matrix(ncol=n_location, nrow=n_humans, data=0)
    for (i in 1:nrow(humanData)) {
        sus = humanData[i, 'Age']
        if(sus>=6 && sus <= 20){
            susResult=0
        }else{
            susResult=1
        }
        hum = as.numeric(unlist(strsplit(as.character(humanData[i,"Human"]),"Human"))[[2]])
        loc = as.numeric(unlist(strsplit(as.character(humanData[i,'marker']),'X'))[[2]])
        dm[hum, loc] = susResult
    }
    result <- as.data.frame(dm)
    row.names(result) <- c(paste("H",1:nrow(result), sep=''))
    names(result) <- c(paste("L",1:length(names(result)), sep=''))
    return(result)
}

In [25]:
As <- generateAs(locationMarker, humanM)
As

   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1 1  0  0  0  0  0  0  0  0  0   0   0   1   0   0   0
H2 0  0  0  0  0  0  0  0  0  0   1   0   0   0   0   0
H3 0  0  1  0  0  0  0  0  0  0   0   0   0   0   0   0
H4 0  0  0  0  0  0  0  0  0  0   0   1   0   0   0   0
H5 0  0  0  1  0  0  0  0  1  0   0   0   0   0   0   0
H6 0  0  0  0  0  0  0  0  0  1   0   0   0   0   0   0
H7 0  0  0  0  0  1  0  0  0  0   0   0   0   1   0   0
H8 0  1  0  0  0  0  1  0  0  0   0   0   0   0   0   1

## P

In [26]:
generatePr <- function(locations, humanData){
    n_humans = length(unique(humanData[,'Human']))
    n_location = length(unique(locations[,'marker']))
    dm = matrix(ncol=n_location, nrow=n_humans, data=0)
    for (i in 1:nrow(humanData)) {
        sus = humanData[i, 'Pregnancy']
        hum = as.numeric(unlist(strsplit(as.character(humanData[i,"Human"]),"Human"))[[2]])
        loc = as.numeric(unlist(strsplit(as.character(humanData[i,'marker']),'X'))[[2]])
        dm[hum, loc] = sus
    }
    result <- as.data.frame(dm)
    row.names(result) <- c(paste("H",1:nrow(result), sep=''))
    names(result) <- c(paste("L",1:length(names(result)), sep=''))
    return(result)
}

In [27]:
Pr <- generatePr(locationMarker, humanM)
Pr

   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1 1  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0
H2 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0
H3 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0
H4 0  0  0  0  0  0  0  0  0  0   0   1   0   0   0   0
H5 0  0  0  0  0  0  0  0  1  0   0   0   0   0   0   0
H6 0  0  0  0  0  0  0  0  0  1   0   0   0   0   0   0
H7 0  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0
H8 0  0  0  0  0  0  1  0  0  0   0   0   0   0   0   0

# Quantification of link weight
## Link weight
$MCS_{i,j} = \sum{\textrm{Human node parameter}_j} + \sum{\textrm{Location node parameter}_i}= (Fh_{j,i} + Du_{j,i} + V_{j,i} + As_{j,i}+P_{j,i} ) + (Fl_i + Dp_i + Sl_i )$

In [28]:
locParameters <- c()
locParameters$n_loc <- length(unique(locationMarker$marker))
locParameters$Fl <- FL
locParameters$Dp <- DP
locParameters$Sl <- SL
locParameters

$n_loc
[1] 16

$Fl
 [1] 0 0 0 0 0 0 2 0 1 0 0 0 0 1 0 4

$Dp
 [1]     0     0     0     0     0     0 20123     0 12500     0     0     0
[13]     0 10230     0 47600

$Sl
 [1] 1200 1300 1400 1250 1350 1240 1350 1360 1400 1430 1450 2000 1100 1150 1900
[16] 1750

In [29]:
humParameters <- c()
humParameters$n_hum <- length(unique(humanM$Human))
humParameters$Fh <- FHM
humParameters$Du <- DU
humParameters$V <- Vp
humParameters$As <- As
humParameters$P <- Pr
humParameters

$n_hum
[1] 8

$Fh
   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1  1  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0
H2  0  0  0  0  0  0  0  0  0   0   2   0   0   0   0   0
H3  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0
H4  0  0  0  0  0  0  1  2  0   0   0   1   0   0   0   0
H5  0  0  0  3  0  0  0  0  1   0   0   0   0   0   1   0
H6  0  0  0  0  1  0  0  0  0   3   0   0   0   0   0   0
H7  0  0  0  0  0  2  0  0  0   0   0   0   0   1   0   0
H8  0  1  0  0  0  0  2  0  0   0   0   0   0   0   0   1

$Du
      L1    L2    L3    L4    L5    L6    L7    L8    L9   L10   L11   L12
H1 28800     0     0     0     0     0     0     0     0     0     0     0
H2     0     0     0     0     0     0     0     0     0     0 20123     0
H3     0     0 12500     0     0     0     0     0     0     0     0     0
H4     0     0     0     0     0     0 10230 21600     0     0     0 12600
H5     0     0     0 37800     0     0     0     0 14400     0     0     0
H6     0     0     0     0 10800     0     0     0     0 21600     0     0
H7     0     0     0     0     0 25200     0     0     0     0     0     0
H8     0 22680     0     0     0     0 18000     0     0     0     0     0
     L13   L14  L15   L16
H1 18800     0    0     0
H2     0     0    0     0
H3     0     0    0     0
H4     0     0    0     0
H5     0     0 9000     0
H6     0     0    0     0
H7     0 13320    0     0
H8     0     0    0 27000

$V
   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1  2  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0
H2  0  0  0  0  0  0  0  0  0   0   2   0   0   0   0   0
H3  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0
H4  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0
H5  0  0  0  0  0  0  0  0  1   0   0   0   0   0   0   0
H6  0  0  0  0  1  0  0  0  0   1   0   0   0   0   0   0
H7  0  0  0  0  0  1  0  0  0   0   0   0   0   2   0   0
H8  0  2  0  0  0  0  2  0  0   0   0   0   0   0   0   2

$As
   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1  1  0  0  0  0  0  0  0  0   0   0   0   1   0   0   0
H2  0  0  0  0  0  0  0  0  0   0   1   0   0   0   0   0
H3  0  0  1  0  0  0  0  0  0   0   0   0   0   0   0   0
H4  0  0  0  0  0  0  0  0  0   0   0   1   0   0   0   0
H5  0  0  0  1  0  0  0  0  1   0   0   0   0   0   0   0
H6  0  0  0  0  0  0  0  0  0   1   0   0   0   0   0   0
H7  0  0  0  0  0  1  0  0  0   0   0   0   0   1   0   0
H8  0  1  0  0  0  0  1  0  0   0   0   0   0   0   0   1

$P
   L1 L2 L3 L4 L5 L6 L7 L8 L9 L10 L11 L12 L13 L14 L15 L16
H1  1  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0
H2  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0
H3  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0
H4  0  0  0  0  0  0  0  0  0   0   0   1   0   0   0   0
H5  0  0  0  0  0  0  0  0  1   0   0   0   0   0   0   0
H6  0  0  0  0  0  0  0  0  0   1   0   0   0   0   0   0
H7  0  0  0  0  0  0  0  0  0   0   0   0   0   0   0   0
H8  0  0  0  0  0  0  1  0  0   0   0   0   0   0   0   0

In [30]:
normalise<-function(parameters){
    for (c in names(parameters)){
        if (c!= 'n_loc' && c!='n_hum'){
            parameters[[`c`]] <- round(((parameters[[`c`]]/max(parameters[[`c`]]))*0.9),digits = 4)
        }
    }
    return(parameters)
}
normLocParameters <- normalise(locParameters)
normLocParameters
normHumParameters <- normalise(humParameters)
normHumParameters

$n_loc
[1] 16

$Fl
 [1] 0.000 0.000 0.000 0.000 0.000 0.000 0.450 0.000 0.225 0.000 0.000 0.000
[13] 0.000 0.225 0.000 0.900

$Dp
 [1] 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.3805 0.0000 0.2363 0.0000
[11] 0.0000 0.0000 0.0000 0.1934 0.0000 0.9000

$Sl
 [1] 0.5400 0.5850 0.6300 0.5625 0.6075 0.5580 0.6075 0.6120 0.6300 0.6435
[11] 0.6525 0.9000 0.4950 0.5175 0.8550 0.7875

$n_hum
[1] 8

$Fh
    L1  L2  L3  L4  L5  L6  L7  L8  L9 L10 L11 L12 L13 L14 L15 L16
H1 0.3 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.3 0.0 0.0 0.0
H2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.6 0.0 0.0 0.0 0.0 0.0
H3 0.0 0.0 0.3 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
H4 0.0 0.0 0.0 0.0 0.0 0.0 0.3 0.6 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.0
H5 0.0 0.0 0.0 0.9 0.0 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.0 0.0 0.3 0.0
H6 0.0 0.0 0.0 0.0 0.3 0.0 0.0 0.0 0.0 0.9 0.0 0.0 0.0 0.0 0.0 0.0
H7 0.0 0.0 0.0 0.0 0.0 0.6 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.3 0.0 0.0
H8 0.0 0.3 0.0 0.0 0.0 0.0 0.6 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.3

$Du
       L1   L2     L3  L4     L5  L6     L7     L8     L9    L10    L11 L12
H1 0.6857 0.00 0.0000 0.0 0.0000 0.0 0.0000 0.0000 0.0000 0.0000 0.0000 0.0
H2 0.0000 0.00 0.0000 0.0 0.0000 0.0 0.0000 0.0000 0.0000 0.0000 0.4791 0.0
H3 0.0000 0.00 0.2976 0.0 0.0000 0.0 0.0000 0.0000 0.0000 0.0000 0.0000 0.0
H4 0.0000 0.00 0.0000 0.0 0.0000 0.0 0.2436 0.5143 0.0000 0.0000 0.0000 0.3
H5 0.0000 0.00 0.0000 0.9 0.0000 0.0 0.0000 0.0000 0.3429 0.0000 0.0000 0.0
H6 0.0000 0.00 0.0000 0.0 0.2571 0.0 0.0000 0.0000 0.0000 0.5143 0.0000 0.0
H7 0.0000 0.00 0.0000 0.0 0.0000 0.6 0.0000 0.0000 0.0000 0.0000 0.0000 0.0
H8 0.0000 0.54 0.0000 0.0 0.0000 0.0 0.4286 0.0000 0.0000 0.0000 0.0000 0.0
      L13    L14    L15    L16
H1 0.4476 0.0000 0.0000 0.0000
H2 0.0000 0.0000 0.0000 0.0000
H3 0.0000 0.0000 0.0000 0.0000
H4 0.0000 0.0000 0.0000 0.0000
H5 0.0000 0.0000 0.2143 0.0000
H6 0.0000 0.0000 0.0000 0.0000
H7 0.0000 0.3171 0.0000 0.0000
H8 0.0000 0.0000 0.0000 0.6429

$V
    L1  L2   L3 L4   L5   L6   L7 L8   L9  L10 L11 L12  L13 L14 L15 L16
H1 0.9 0.0 0.00  0 0.00 0.00 0.00  0 0.00 0.00 0.0   0 0.45 0.0   0 0.0
H2 0.0 0.0 0.00  0 0.00 0.00 0.00  0 0.00 0.00 0.9   0 0.00 0.0   0 0.0
H3 0.0 0.0 0.45  0 0.00 0.00 0.00  0 0.00 0.00 0.0   0 0.00 0.0   0 0.0
H4 0.0 0.0 0.00  0 0.00 0.00 0.45  0 0.00 0.00 0.0   0 0.00 0.0   0 0.0
H5 0.0 0.0 0.00  0 0.00 0.00 0.00  0 0.45 0.00 0.0   0 0.00 0.0   0 0.0
H6 0.0 0.0 0.00  0 0.45 0.00 0.00  0 0.00 0.45 0.0   0 0.00 0.0   0 0.0
H7 0.0 0.0 0.00  0 0.00 0.45 0.00  0 0.00 0.00 0.0   0 0.00 0.9   0 0.0
H8 0.0 0.9 0.00  0 0.00 0.00 0.90  0 0.00 0.00 0.0   0 0.00 0.0   0 0.9

$As
    L1  L2  L3  L4 L5  L6  L7 L8  L9 L10 L11 L12 L13 L14 L15 L16
H1 0.9 0.0 0.0 0.0  0 0.0 0.0  0 0.0 0.0 0.0 0.0 0.9 0.0   0 0.0
H2 0.0 0.0 0.0 0.0  0 0.0 0.0  0 0.0 0.0 0.9 0.0 0.0 0.0   0 0.0
H3 0.0 0.0 0.9 0.0  0 0.0 0.0  0 0.0 0.0 0.0 0.0 0.0 0.0   0 0.0
H4 0.0 0.0 0.0 0.0  0 0.0 0.0  0 0.0 0.0 0.0 0.9 0.0 0.0   0 0.0
H5 0.0 0.0 0.0 0.9  0 0.0 0.0  0 0.9 0.0 0.0 0.0 0.0 0.0   0 0.0
H6 0.0 0.0 0.0 0.0  0 0.0 0.0  0 0.0 0.9 0.0 0.0 0.0 0.0   0 0.0
H7 0.0 0.0 0.0 0.0  0 0.9 0.0  0 0.0 0.0 0.0 0.0 0.0 0.9   0 0.0
H8 0.0 0.9 0.0 0.0  0 0.0 0.9  0 0.0 0.0 0.0 0.0 0.0 0.0   0 0.9

$P
    L1 L2 L3 L4 L5 L6  L7 L8  L9 L10 L11 L12 L13 L14 L15 L16
H1 0.9  0  0  0  0  0 0.0  0 0.0 0.0   0 0.0   0   0   0   0
H2 0.0  0  0  0  0  0 0.0  0 0.0 0.0   0 0.0   0   0   0   0
H3 0.0  0  0  0  0  0 0.0  0 0.0 0.0   0 0.0   0   0   0   0
H4 0.0  0  0  0  0  0 0.0  0 0.0 0.0   0 0.9   0   0   0   0
H5 0.0  0  0  0  0  0 0.0  0 0.9 0.0   0 0.0   0   0   0   0
H6 0.0  0  0  0  0  0 0.0  0 0.0 0.9   0 0.0   0   0   0   0
H7 0.0  0  0  0  0  0 0.0  0 0.0 0.0   0 0.0   0   0   0   0
H8 0.0  0  0  0  0  0 0.9  0 0.0 0.0   0 0.0   0   0   0   0

In [31]:
generateLinkWeight <- function(locationParameters, humanParameters, linkMatrix){
    n_location = locationParameters$n_loc
    n_human = humanParameters$n_hum
    
    #for (c in names(locationParameters)){
    #    if (c!= 'n_loc'){
    #        locationParameters[[`c`]] <- round(((locationParameters[[`c`]]/max(locationParameters[[`c`]]))*0.9),digits = 4)
    #    }
    #}
    #for (c in names(humanParameters)){
    #    if (c!= 'n_hum'){
    #        humanParameters[[`c`]] <- round(((humanParameters[[`c`]]/max(humanParameters[[`c`]]))*0.9),digits = 4)
    #    }
    #}
    
    dm = matrix(nrow = n_location, ncol = n_human, data = 0)
    for (i in 1:n_location){
        locationSum = locationParameters$Fl[i] + locationParameters$Dp[i] + locationParameters$Sl[i]
        #print(paste("location", i, ":", locationSum))
        for (j in 1:n_human){
            humanSum = humanParameters$Fh[j,i] + humanParameters$Du[j,i] + humanParameters$V[j,i] + humanParameters$As[j,i] + humanParameters$P[j,i]
            dm[i,j] = locationSum + humanSum
            #print(paste("human", j, ":", humanSum))
            #print(paste("Total:", locationSum + humanSum))
        }
    }
    result <- as.data.frame(dm)
    row.names(result) <- c(paste("L",1:nrow(result), sep=''))
    names(result) <- c(paste("H",1:length(names(result)), sep=''))
    return(result*linkMatrix)
}

In [32]:
linkWeight <- generateLinkWeight(normLocParameters, normHumParameters, lnkMtrxH)
print(linkWeight)

        H1     H2     H3     H4     H5     H6    H7     H8
L1  4.2257 0.0000 0.0000 0.0000 0.0000 0.0000 0.000 0.0000
L2  0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.000 3.2250
L3  0.0000 0.0000 2.5776 0.0000 0.0000 0.0000 0.000 0.0000
L4  0.0000 0.0000 0.0000 0.0000 3.2625 0.0000 0.000 0.0000
L5  0.0000 0.0000 0.0000 0.0000 0.0000 1.6146 0.000 0.0000
L6  0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 3.108 0.0000
L7  0.0000 0.0000 0.0000 2.4316 0.0000 0.0000 0.000 5.1666
L8  0.0000 0.0000 0.0000 1.7263 0.0000 0.0000 0.000 0.0000
L9  0.0000 0.0000 0.0000 0.0000 3.9842 0.0000 0.000 0.0000
L10 0.0000 0.0000 0.0000 0.0000 0.0000 4.3078 0.000 0.0000
L11 0.0000 3.5316 0.0000 0.0000 0.0000 0.0000 0.000 0.0000
L12 0.0000 0.0000 0.0000 3.3000 0.0000 0.0000 0.000 0.0000
L13 2.5926 0.0000 0.0000 0.0000 0.0000 0.0000 0.000 0.0000
L14 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 3.353 0.0000
L15 0.0000 0.0000 0.0000 0.0000 1.3693 0.0000 0.000 0.0000
L16 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.000 5.3304

In [33]:
write.csv(linkWeight, "weight.csv")

# HITS Search
## Hub
$ Hub = MCS \times MCS^T$

In [34]:
Hub = as.matrix(linkWeight) %*% t(linkWeight)
Hub

    L1       L2       L3       L4        L5       L6        L7        L8
L1  17.85654  0.00000 0.000000  0.000000 0.000000  0.000000  0.000000 0.000000
L2   0.00000 10.40062 0.000000  0.000000 0.000000  0.000000 16.662285 0.000000
L3   0.00000  0.00000 6.644022  0.000000 0.000000  0.000000  0.000000 0.000000
L4   0.00000  0.00000 0.000000 10.643906 0.000000  0.000000  0.000000 0.000000
L5   0.00000  0.00000 0.000000  0.000000 2.606933  0.000000  0.000000 0.000000
L6   0.00000  0.00000 0.000000  0.000000 0.000000  9.659664  0.000000 0.000000
L7   0.00000 16.66229 0.000000  0.000000 0.000000  0.000000 32.606434 4.197671
L8   0.00000  0.00000 0.000000  0.000000 0.000000  0.000000  4.197671 2.980112
L9   0.00000  0.00000 0.000000 12.998453 0.000000  0.000000  0.000000 0.000000
L10  0.00000  0.00000 0.000000  0.000000 6.955374  0.000000  0.000000 0.000000
L11  0.00000  0.00000 0.000000  0.000000 0.000000  0.000000  0.000000 0.000000
L12  0.00000  0.00000 0.000000  0.000000 0.000000  0.000000  8.024280 5.696790
L13 10.95555  0.00000 0.000000  0.000000 0.000000  0.000000  0.000000 0.000000
L14  0.00000  0.00000 0.000000  0.000000 0.000000 10.421124  0.000000 0.000000
L15  0.00000  0.00000 0.000000  4.467341 0.000000  0.000000  0.000000 0.000000
L16  0.00000 17.19054 0.000000  0.000000 0.000000  0.000000 27.540045 0.000000
    L9        L10       L11     L12      L13       L14      L15      L16
L1   0.000000  0.000000  0.0000  0.00000 10.955550  0.00000 0.000000  0.00000
L2   0.000000  0.000000  0.0000  0.00000  0.000000  0.00000 0.000000 17.19054
L3   0.000000  0.000000  0.0000  0.00000  0.000000  0.00000 0.000000  0.00000
L4  12.998453  0.000000  0.0000  0.00000  0.000000  0.00000 4.467341  0.00000
L5   0.000000  6.955374  0.0000  0.00000  0.000000  0.00000 0.000000  0.00000
L6   0.000000  0.000000  0.0000  0.00000  0.000000 10.42112 0.000000  0.00000
L7   0.000000  0.000000  0.0000  8.02428  0.000000  0.00000 0.000000 27.54004
L8   0.000000  0.000000  0.0000  5.69679  0.000000  0.00000 0.000000  0.00000
L9  15.873850  0.000000  0.0000  0.00000  0.000000  0.00000 5.455565  0.00000
L10  0.000000 18.557141  0.0000  0.00000  0.000000  0.00000 0.000000  0.00000
L11  0.000000  0.000000 12.4722  0.00000  0.000000  0.00000 0.000000  0.00000
L12  0.000000  0.000000  0.0000 10.89000  0.000000  0.00000 0.000000  0.00000
L13  0.000000  0.000000  0.0000  0.00000  6.721575  0.00000 0.000000  0.00000
L14  0.000000  0.000000  0.0000  0.00000  0.000000 11.24261 0.000000  0.00000
L15  5.455565  0.000000  0.0000  0.00000  0.000000  0.00000 1.874982  0.00000
L16  0.000000  0.000000  0.0000  0.00000  0.000000  0.00000 0.000000 28.41316

In [35]:
write.csv(Hub, "hub.csv")

## Authority
$Authority = MCS^T \times MCS$

In [36]:
Authority = t(linkWeight)%*%as.matrix(linkWeight)
Authority

   H1       H2      H3       H4       H5       H6       H7       H8
H1 24.57812  0.0000 0.000000  0.00000  0.00000  0.00000  0.00000  0.00000
H2  0.00000 12.4722 0.000000  0.00000  0.00000  0.00000  0.00000  0.00000
H3  0.00000  0.0000 6.644022  0.00000  0.00000  0.00000  0.00000  0.00000
H4  0.00000  0.0000 0.000000 19.78279  0.00000  0.00000  0.00000 12.56310
H5  0.00000  0.0000 0.000000  0.00000 28.39274  0.00000  0.00000  0.00000
H6  0.00000  0.0000 0.000000  0.00000  0.00000 21.16407  0.00000  0.00000
H7  0.00000  0.0000 0.000000  0.00000  0.00000  0.00000 20.90227  0.00000
H8  0.00000  0.0000 0.000000 12.56310  0.00000  0.00000  0.00000 65.50754

In [37]:
write.csv(Authority, "authority.csv")

In [38]:
is_square_matrix <- function(A){
    return(nrow(A)==ncol(A))
}

eucNorm <- function(A){
    A <- matrix(A, ncol=1)
    return(sqrt(colSums(A^2)))
}

powerMethod <- function(matrix, startVector = NULL, threshold = 1e-6, maxIteration = 100){
    if (!is_square_matrix(matrix)){
        stop("'powerMethod()' requires a square numeric matrix")
    }
    if (is.null(startVector)){
        startVector = rep(1, nrow(matrix))
    }
    cachedVector = startVector
    steps = 1
    vectors <- list(startVector)
    while(TRUE){
        v_new = matrix %*% cachedVector
        # 4.21
        v_new = v_new/eucNorm(v_new)
        if (eucNorm(abs(v_new) - abs(cachedVector)) <= threshold){
            break}
        cachedVector = v_new
        steps = steps + 1
        vectors[[steps]] <- c(v_new)
        if (steps == maxIteration){
            break}
    }
    lambda = sum((matrix %*% v_new) * v_new)
    res <- list(iter = steps, vector = v_new, value = lambda)
    vectors <- do.call(cbind, vectors)
    colnames(vectors) <- paste0("v", 1:ncol(vectors))
    res <- c(vector_iterations=list(vectors), res)
    return(res)
}

In [39]:
k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)

In [40]:
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)

In [41]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')
humanRank
locationRank

  MHRbmc       Human
1 1.000000e+00 H8
2 2.567795e-01 H4
3 4.214961e-03 H5
4 1.773541e-03 H1
5 7.230120e-04 H6
6 6.709822e-04 H7
7 3.028363e-05 H2
8 6.920479e-07 H3

   MHRbmc       Location
1  1.000000e+00 L7
2  9.204287e-01 L16
3  5.568780e-01 L2
4  1.463741e-01 L12
5  7.657142e-02 L8
6  4.860932e-03 L9
7  3.980420e-03 L4
8  1.983143e-03 L1
9  1.670617e-03 L15
10 1.216720e-03 L13
11 8.313539e-04 L10
12 6.633415e-04 L14
13 6.148719e-04 L6
14 3.115985e-04 L5
15 2.888647e-05 L11
16 6.601195e-07 L3

In [42]:
ih

$vector_iterations
     v1         v2          v3           v4           v5           v6
[1,]  1 0.25037984 0.102792509 0.0374553608 1.342793e-02 4.803497e-03
[2,]  1 0.12705560 0.026469781 0.0048943757 8.904032e-04 1.616329e-04
[3,]  1 0.06768335 0.007511495 0.0007398802 7.170325e-05 6.933777e-06
[4,]  1 0.32951103 0.275782957 0.2558478529 2.504210e-01 2.490476e-01
[5,]  1 0.28923981 0.137176234 0.0577417707 2.391353e-02 9.882140e-03
[6,]  1 0.21560065 0.076218932 0.0239147624 7.382640e-03 2.274107e-03
[7,]  1 0.21293365 0.074344928 0.0230382137 7.024068e-03 2.136890e-03
[8,]  1 0.79531391 0.939396921 0.9636792426 9.676944e-01 9.684239e-01

$iter
[1] 6

$vector
           [,1]
H1 1.717795e-03
H2 2.933175e-05
H3 6.702953e-07
H4 2.487083e-01
H5 4.082476e-03
H6 7.002862e-04
H7 6.498917e-04
H8 9.685678e-01

$value
[1] 68.7311

# Benchmark verification
1. Reading the result

In [43]:
uci_human <- read.csv('UCI_Auth.csv')
uci_location <- read.csv('UCI_Hub.csv')
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")
uci_human
uci_location

  Human MHRb
1 H1       38.238
2 H2       15.234
3 H3        7.354
4 H4    20813.227
5 H5       48.343
6 H6       30.567
7 H7       30.024
8 H8    81030.633

   Location MHRb
1  L1          44.825
2  L2       47306.453
3  L3           7.354
4  L4          47.861
5  L5          13.811
6  L6          28.844
7  L7       84954.242
8  L8        6508.130
9  L9          58.448
10 L10         36.847
11 L11         15.234
12 L12      12440.961
13 L13         27.502
14 L14         31.118
15 L15         20.088
16 L16      78189.867

2. Calibrate result to 0-1

In [44]:
uci_human$MHRb <- uci_human$MHRb/max(uci_human$MHRb)
uci_location$MHRb <- uci_location$MHRb/max(uci_location$MHRb)
uci_human
uci_location

  Human MHRb
1 H1    0.0004718956
2 H2    0.0001880030
3 H3    0.0000907558
4 H4    0.2568562805
5 H5    0.0005966015
6 H6    0.0003772277
7 H7    0.0003705265
8 H8    1.0000000000

   Location MHRb
1  L1       5.276370e-04
2  L2       5.568463e-01
3  L3       8.656425e-05
4  L4       5.633739e-04
5  L5       1.625699e-04
6  L6       3.395240e-04
7  L7       1.000000e+00
8  L8       7.660748e-02
9  L9       6.879939e-04
10 L10      4.337276e-04
11 L11      1.793201e-04
12 L12      1.464431e-01
13 L13      3.237272e-04
14 L14      3.662913e-04
15 L15      2.364567e-04
16 L16      9.203763e-01

3. Calculating RMSE

In [45]:
human_compare <- merge(uci_human, humanRank, by='Human')
location_compare <- merge(uci_location, locationRank, by='Location')
human_compare$`MHRb - MHRbmc` <- human_compare$MHRb - human_compare$MHRbmc
location_compare$`MHRb - MHRbmc` <- location_compare$MHRb - location_compare$MHRbmc
human_compare$`(MHRb - MHRbmc)^2` <- (human_compare$`MHRb - MHRbmc`)^2
location_compare$`(MHRb - MHRbmc)^2` <- (location_compare$`MHRb - MHRbmc`)^2
human_compare
print(paste("SUM of (MHR_B-MHR_BMCNet)^2:", sum(human_compare$`(MHRb - MHRbmc)^2`)))
print(paste("RMSE:", sqrt(sum(human_compare$`(MHRb - MHRbmc)^2`)/length(human_compare$`(MHRb - MHRbmc)^2`))))
location_compare[order(as.numeric(gsub("L","", location_compare$Location))),]
print(paste("SUM of (MHR_B-MHR_BMCNet)^2:", sum(location_compare$`(MHRb - MHRbmc)^2`)))
print(paste("RMSE:", sqrt(sum(location_compare$`(MHRb - MHRbmc)^2`)/length(location_compare$`(MHRb - MHRbmc)^2`))))

  Human MHRb         MHRbmc       MHRb - MHRbmc (MHRb - MHRbmc)^2
1 H1    0.0004718956 1.773541e-03 -1.301646e-03 1.694282e-06
2 H2    0.0001880030 3.028363e-05  1.577193e-04 2.487539e-08
3 H3    0.0000907558 6.920479e-07  9.006375e-05 8.111480e-09
4 H4    0.2568562805 2.567795e-01  7.679542e-05 5.897536e-09
5 H5    0.0005966015 4.214961e-03 -3.618359e-03 1.309253e-05
6 H6    0.0003772277 7.230120e-04 -3.457843e-04 1.195668e-07
7 H7    0.0003705265 6.709822e-04 -3.004556e-04 9.027358e-08
8 H8    1.0000000000 1.000000e+00  0.000000e+00 0.000000e+00

[1] "SUM of (MHR_B-MHR_BMCNet)^2: 1.50355318932529e-05"
[1] "RMSE: 0.00137092723609118"

   Location MHRb         MHRbmc       MHRb - MHRbmc (MHRb - MHRbmc)^2
1  L1       5.276370e-04 1.983143e-03 -1.455506e-03 2.118497e-06
9  L2       5.568463e-01 5.568780e-01 -3.171319e-05 1.005727e-09
10 L3       8.656425e-05 6.601195e-07  8.590413e-05 7.379519e-09
11 L4       5.633739e-04 3.980420e-03 -3.417046e-03 1.167621e-05
12 L5       1.625699e-04 3.115985e-04 -1.490286e-04 2.220953e-08
13 L6       3.395240e-04 6.148719e-04 -2.753479e-04 7.581648e-08
14 L7       1.000000e+00 1.000000e+00  0.000000e+00 0.000000e+00
15 L8       7.660748e-02 7.657142e-02  3.605627e-05 1.300055e-09
16 L9       6.879939e-04 4.860932e-03 -4.172938e-03 1.741341e-05
2  L10      4.337276e-04 8.313539e-04 -3.976263e-04 1.581067e-07
3  L11      1.793201e-04 2.888647e-05  1.504336e-04 2.263027e-08
4  L12      1.464431e-01 1.463741e-01  6.893874e-05 4.752550e-09
5  L13      3.237272e-04 1.216720e-03 -8.929932e-04 7.974369e-07
6  L14      3.662913e-04 6.633415e-04 -2.970502e-04 8.823883e-08
7  L15      2.364567e-04 1.670617e-03 -1.434161e-03 2.056817e-06
8  L16      9.203763e-01 9.204287e-01 -5.240213e-05 2.745983e-09

[1] "SUM of (MHR_B-MHR_BMCNet)^2: 3.44465523636361e-05"
[1] "RMSE: 0.00146727963344662"

## SRCC
1. Get the ranking from BMC and UCI

In [46]:
#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
locationRank

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
uci_location

  MHRbmc       Human rank_bmc
1 1.000000e+00 H8    1
2 2.567795e-01 H4    2
3 4.214961e-03 H5    3
4 1.773541e-03 H1    4
5 7.230120e-04 H6    5
6 6.709822e-04 H7    6
7 3.028363e-05 H2    7
8 6.920479e-07 H3    8

   MHRbmc       Location rank_bmc
1  1.000000e+00 L7        1
2  9.204287e-01 L16       2
3  5.568780e-01 L2        3
4  1.463741e-01 L12       4
5  7.657142e-02 L8        5
6  4.860932e-03 L9        6
7  3.980420e-03 L4        7
8  1.983143e-03 L1        8
9  1.670617e-03 L15       9
10 1.216720e-03 L13      10
11 8.313539e-04 L10      11
12 6.633415e-04 L14      12
13 6.148719e-04 L6       13
14 3.115985e-04 L5       14
15 2.888647e-05 L11      15
16 6.601195e-07 L3       16

  Human MHRb         rank_b
1 H1    0.0004718956 4
2 H2    0.0001880030 7
3 H3    0.0000907558 8
4 H4    0.2568562805 2
5 H5    0.0005966015 3
6 H6    0.0003772277 5
7 H7    0.0003705265 6
8 H8    1.0000000000 1

   Location MHRb         rank_b
1  L1       5.276370e-04  8
2  L2       5.568463e-01  3
3  L3       8.656425e-05 16
4  L4       5.633739e-04  7
5  L5       1.625699e-04 15
6  L6       3.395240e-04 11
7  L7       1.000000e+00  1
8  L8       7.660748e-02  5
9  L9       6.879939e-04  6
10 L10      4.337276e-04  9
11 L11      1.793201e-04 14
12 L12      1.464431e-01  4
13 L13      3.237272e-04 12
14 L14      3.662913e-04 10
15 L15      2.364567e-04 13
16 L16      9.203763e-01  2

2. Compute the value

In [47]:
human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb         rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1    0.0004718956 4      1.773541e-03 4        0      0
2 H2    0.0001880030 7      3.028363e-05 7        0      0
3 H3    0.0000907558 8      6.920479e-07 8        0      0
4 H4    0.2568562805 2      2.567795e-01 2        0      0
5 H5    0.0005966015 3      4.214961e-03 3        0      0
6 H6    0.0003772277 5      7.230120e-04 5        0      0
7 H7    0.0003705265 6      6.709822e-04 6        0      0
8 H8    1.0000000000 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb         rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1       5.276370e-04  8     1.983143e-03  8        0      0
9  L2       5.568463e-01  3     5.568780e-01  3        0      0
10 L3       8.656425e-05 16     6.601195e-07 16        0      0
11 L4       5.633739e-04  7     3.980420e-03  7        0      0
12 L5       1.625699e-04 15     3.115985e-04 14       -1      1
13 L6       3.395240e-04 11     6.148719e-04 13        2      4
14 L7       1.000000e+00  1     1.000000e+00  1        0      0
15 L8       7.660748e-02  5     7.657142e-02  5        0      0
16 L9       6.879939e-04  6     4.860932e-03  6        0      0
2  L10      4.337276e-04  9     8.313539e-04 11        2      4
3  L11      1.793201e-04 14     2.888647e-05 15        1      1
4  L12      1.464431e-01  4     1.463741e-01  4        0      0
5  L13      3.237272e-04 12     1.216720e-03 10       -2      4
6  L14      3.662913e-04 10     6.633415e-04 12        2      4
7  L15      2.364567e-04 13     1.670617e-03  9       -4     16
8  L16      9.203763e-01  2     9.204287e-01  2        0      0

[1] "Sum of d Rank^2: 34"
[1] "P: 0.95018315018315"

## Parameter significance analysis
### Leave one out
1. Fl

In [48]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
linkWeight <- generateLinkWeight(new_normLocParameters, normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wFl.csv")
write.csv(Hub, "hub_wFl.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  3.437467e-03
L2  6.178747e-01
L3  3.093069e-07
L4  5.308431e-03
L5  4.650832e-04
L6  5.668649e-04
L7  1.000000e+00
L8  8.393762e-02
L9  6.116614e-03
L10 1.240856e-03
L11 2.540817e-05
L12 1.604554e-01
L13 2.108994e-03
L14 5.705127e-04
L15 2.227995e-03
L16 8.488162e-01

   [,1]
H1 3.161150e-03
H2 2.739089e-05
H3 3.334436e-07
H4 2.537304e-01
H5 5.571083e-03
H6 1.109686e-03
H7 6.130726e-04
H8 1.000000e+00

In [49]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wFl.csv') #Replace here
uci_location <- read.csv('c_result/hub_wFl.csv') # Replace here
uci_human
uci_location
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb
1 H1       44.632
2 H2       16.156
3 H3        7.563
4 H4    16340.707
5 H5       51.971
6 H6       34.520
7 H7       30.167
8 H8    64361.617

   Location MHRb
1  L1          52.321
2  L2       42870.094
3  L3           7.563
4  L4          53.385
5  L5          15.597
6  L6          30.070
7  L7       69389.953
8  L8        5829.780
9  L9          61.513
10 L10         41.613
11 L11         16.156
12 L12      11144.225
13 L13         32.101
14 L14         30.264
15 L15         22.406
16 L16      58893.543

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       44.632 4      3.161150e-03 4        0      0
2 H2       16.156 7      2.739089e-05 7        0      0
3 H3        7.563 8      3.334436e-07 8        0      0
4 H4    16340.707 2      2.537304e-01 2        0      0
5 H5       51.971 3      5.571083e-03 3        0      0
6 H6       34.520 5      1.109686e-03 5        0      0
7 H7       30.167 6      6.130726e-04 6        0      0
8 H8    64361.617 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          52.321  8     3.437467e-03  8        0      0
9  L2       42870.094  3     6.178747e-01  3        0      0
10 L3           7.563 16     3.093069e-07 16        0      0
11 L4          53.385  7     5.308431e-03  7        0      0
12 L5          15.597 15     4.650832e-04 14       -1      1
13 L6          30.070 12     5.668649e-04 13        1      1
14 L7       69389.953  1     1.000000e+00  1        0      0
15 L8        5829.780  5     8.393762e-02  5        0      0
16 L9          61.513  6     6.116614e-03  6        0      0
2  L10         41.613  9     1.240856e-03 11        2      4
3  L11         16.156 14     2.540817e-05 15        1      1
4  L12      11144.225  4     1.604554e-01  4        0      0
5  L13         32.101 10     2.108994e-03 10        0      0
6  L14         30.264 11     5.705127e-04 12        1      1
7  L15         22.406 13     2.227995e-03  9       -4     16
8  L16      58893.543  2     8.488162e-01  2        0      0

[1] "Sum of d Rank^2: 24"
[1] "P: 0.964835164835165"

2. Dp

In [50]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
linkWeight <- generateLinkWeight(new_normLocParameters, normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wDp.csv")
write.csv(Hub, "hub_wDp.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  3.047935e-03
L2  6.057163e-01
L3  2.742564e-07
L4  4.611482e-03
L5  4.123802e-04
L6  5.369498e-04
L7  1.000000e+00
L8  8.507311e-02
L9  5.297586e-03
L10 1.100242e-03
L11 2.252893e-05
L12 1.626260e-01
L13 1.870004e-03
L14 5.458644e-04
L15 1.935480e-03
L16 8.321133e-01

   [,1]
H1 2.824734e-03
H2 2.447590e-05
H3 2.979579e-07
H4 2.623309e-01
H5 4.868329e-03
H6 9.915908e-04
H7 5.882358e-04
H8 1.000000e+00

In [51]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wDP.csv') #Replace here
uci_location <- read.csv('c_result/hub_wDp.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       44.072 4      2.824734e-03 4        0      0
2 H2       16.082 7      2.447590e-05 7        0      0
3 H3        7.546 8      2.979579e-07 8        0      0
4 H4    17207.590 2      2.623309e-01 2        0      0
5 H5       50.901 3      4.868329e-03 3        0      0
6 H6       34.184 5      9.915908e-04 5        0      0
7 H7       30.383 6      5.882358e-04 6        0      0
8 H8    65555.180 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          51.665  8     3.047935e-03  8        0      0
9  L2       43138.074  3     6.057163e-01  3        0      0
10 L3           7.546 16     2.742564e-07 16        0      0
11 L4          52.382  7     4.611482e-03  7        0      0
12 L5          15.445 15     4.123802e-04 14       -1      1
13 L6          30.131 12     5.369498e-04 13        1      1
14 L7       71225.414  1     1.000000e+00  1        0      0
15 L8        6064.769  5     8.507311e-02  5        0      0
16 L9          60.176  6     5.297586e-03  6        0      0
2  L10         41.208  9     1.100242e-03 11        2      4
3  L11         16.082 14     2.252893e-05 15        1      1
4  L12      11593.431  4     1.626260e-01  4        0      0
5  L13         31.698 10     1.870004e-03 10        0      0
6  L14         30.631 11     5.458644e-04 12        1      1
7  L15         21.985 13     1.935480e-03  9       -4     16
8  L16      59261.680  2     8.321133e-01  2        0      0

[1] "Sum of d Rank^2: 24"
[1] "P: 0.964835164835165"

3. Sl

In [52]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
linkWeight <- generateLinkWeight(new_normLocParameters, normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wSl.csv")
write.csv(Hub, "hub_wSl.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  2.081163e-03
L2  5.343809e-01
L3  1.545748e-07
L4  2.164496e-03
L5  1.533555e-04
L6  4.635664e-04
L7  1.000000e+00
L8  4.713558e-02
L9  2.688945e-03
L10 5.579788e-04
L11 1.683536e-05
L12 1.015215e-01
L13 1.184428e-03
L14 5.154677e-04
L15 4.122964e-04
L16 9.195603e-01

   [,1]
H1 1.840353e-03
H2 1.764491e-05
H3 1.620077e-07
H4 2.089603e-01
H5 2.405475e-03
H6 4.933831e-04
H7 5.144979e-04
H8 1.000000e+00

In [53]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wSl.csv') #Replace here
uci_location <- read.csv('c_result/hub_wSl.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       28.030 4      1.840353e-03 4        0      0
2 H2        9.929 7      1.764491e-05 7        0      0
3 H3        4.103 8      1.620077e-07 8        0      0
4 H4    12141.147 2      2.089603e-01 2        0      0
5 H5       30.076 3      2.405475e-03 3        0      0
6 H6       20.277 6      4.933831e-04 6        0      0
7 H7       20.477 5      5.144979e-04 5        0      0
8 H8    58068.223 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          33.222  7     2.081163e-03  8        1     1
9  L2       32521.373  3     5.343809e-01  3        0     0
10 L3           4.103 16     1.545748e-07 16        0     0
11 L4          28.365  8     2.164496e-03  7       -1     1
12 L5           6.606 14     1.533555e-04 14        0     0
13 L6          19.337 11     4.635664e-04 12        1     1
14 L7       60863.605  1     1.000000e+00  1        0     0
15 L8        2871.982  5     4.713558e-02  5        0     0
16 L9          35.237  6     2.688945e-03  6        0     0
2  L10         24.034  9     5.579788e-04 10        1     1
3  L11          9.929 13     1.683536e-05 15        2     4
4  L12       6185.729  4     1.015215e-01  4        0     0
5  L13         18.907 12     1.184428e-03  9       -3     9
6  L14         21.502 10     5.154677e-04 11        1     1
7  L15          5.403 15     4.122964e-04 13       -2     4
8  L16      55962.629  2     9.195603e-01  2        0     0

[1] "Sum of d Rank^2: 22"
[1] "P: 0.967765567765568"

4. Fh

In [54]:
#helper function to generate empty dataframe
generateEmpty <- function(n_location, n_humans){
    dm = matrix(ncol=n_location, nrow=n_humans, data=0)
    result <- as.data.frame(dm)
    row.names(result) <- c(paste("H",1:nrow(result), sep=''))
    names(result) <- c(paste("L",1:length(names(result)), sep=''))
    return(result)
}

In [55]:
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wFh.csv")
write.csv(Hub, "hub_wFh.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  2.287916e-03
L2  5.781598e-01
L3  4.843723e-07
L4  1.439921e-03
L5  6.522180e-05
L6  3.214151e-04
L7  1.000000e+00
L8  5.144286e-02
L9  2.245484e-03
L10 1.690726e-04
L11 1.001628e-05
L12 1.370226e-01
L13 1.336138e-03
L14 3.912601e-04
L15 6.517281e-04
L16 9.943163e-01

   [,1]
H1 1.952038e-03
H2 1.009400e-05
H3 4.881306e-07
H4 2.310161e-01
H5 1.752039e-03
H6 1.412506e-04
H7 3.625515e-04
H8 1.000000e+00

In [56]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wFh.csv') #Replace here
uci_location <- read.csv('c_result/hub_wFH.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       32.417 3      1.952038e-03 3        0      0
2 H2       10.120 7      1.009400e-05 7        0      0
3 H3        5.707 8      4.881306e-07 8        0      0
4 H4    15384.786 2      2.310161e-01 2        0      0
5 H5       31.518 4      1.752039e-03 4        0      0
6 H6       17.416 6      1.412506e-04 6        0      0
7 H7       21.496 5      3.625515e-04 5        0      0
8 H8    66564.352 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          38.290  7     2.287916e-03  6       -1     1
9  L2       38782.777  3     5.781598e-01  3        0     0
10 L3           5.707 16     4.843723e-07 16        0     0
11 L4          26.104  8     1.439921e-03  8        0     0
12 L5           8.104 15     6.522180e-05 14       -1     1
13 L6          19.205 12     3.214151e-04 12        0     0
14 L7       67085.141  1     1.000000e+00  1        0     0
15 L8        3453.654  5     5.144286e-02  5        0     0
16 L9          40.708  6     2.245484e-03  7        1     1
2  L10         21.009 11     1.690726e-04 13        2     4
3  L11         10.120 14     1.001628e-05 15        1     1
4  L12       9199.115  4     1.370226e-01  4        0     0
5  L13         22.361 10     1.336138e-03  9       -1     1
6  L14         23.378  9     3.912601e-04 11        2     4
7  L15         11.815 13     6.517281e-04 10       -3     9
8  L16      66698.422  2     9.943163e-01  2        0     0

[1] "Sum of d Rank^2: 22"
[1] "P: 0.967765567765568"

5. Du

In [57]:
new_normHumParameters <- normHumParameters
new_normHumParameters$Du <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wDu.csv")
write.csv(Hub, "hub_wDu.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  9.107541e-04
L2  5.048752e-01
L3  6.050148e-07
L4  1.732900e-03
L5  2.416758e-04
L6  3.822039e-04
L7  1.000000e+00
L8  6.042718e-02
L9  2.670903e-03
L10 6.753570e-04
L11 2.006393e-05
L12 1.495722e-01
L13 5.518552e-04
L14 4.626526e-04
L15 8.471955e-04
L16 8.814162e-01

   [,1]
H1 8.275968e-04
H2 2.141625e-05
H3 6.457933e-07
H4 2.650818e-01
H5 2.206438e-03
H6 5.988804e-04
H7 4.549886e-04
H8 1.000000e+00

In [58]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wDu.csv') #Replace here
uci_location <- read.csv('c_result/hub_wDu.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       25.002 4      8.275968e-04 4        0      0
2 H2       11.242 7      2.141625e-05 7        0      0
3 H3        5.747 8      6.457933e-07 8        0      0
4 H4    17043.055 2      2.650818e-01 2        0      0
5 H5       32.055 3      2.206438e-03 3        0      0
6 H6       23.132 5      5.988804e-04 5        0      0
7 H7       21.684 6      4.549886e-04 6        0      0
8 H8    64270.875 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          29.369  7     9.107541e-04  8        1      1
9  L2       34635.203  3     5.048752e-01  3        0      0
10 L3           5.747 16     6.050148e-07 16        0      0
11 L4          26.873  9     1.732900e-03  7       -2      4
12 L5           9.964 15     2.416758e-04 14       -1      1
13 L6          19.443 11     3.822039e-04 13        2      4
14 L7       68606.086  1     1.000000e+00  1        0      0
15 L8        4147.927  5     6.042718e-02  5        0      0
16 L9          41.419  6     2.670903e-03  6        0      0
2  L10         27.844  8     6.753570e-04 10        2      4
3  L11         11.242 14     2.006393e-05 15        1      1
4  L12      10267.146  4     1.495722e-01  4        0      0
5  L13         17.796 12     5.518552e-04 11       -1      1
6  L14         23.536 10     4.626526e-04 12        2      4
7  L15         13.138 13     8.471955e-04  9       -4     16
8  L16      60466.492  2     8.814162e-01  2        0      0

[1] "Sum of d Rank^2: 36"
[1] "P: 0.947252747252747"

6. V

In [59]:
new_normHumParameters <- normHumParameters
new_normHumParameters$V <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wV.csv")
write.csv(Hub, "hub_wV.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  1.691667e-04
L2  4.778698e-01
L3  7.128886e-09
L4  6.592830e-03
L5  7.043182e-05
L6  3.602484e-05
L7  1.000000e+00
L8  1.072079e-01
L9  7.141878e-03
L10 2.333092e-04
L11 2.139439e-07
L12 2.049389e-01
L13 1.089866e-04
L14 3.324640e-05
L15 2.767069e-03
L16 9.106040e-01

   [,1]
H1 4.567073e-04
H2 1.516766e-06
H3 7.732146e-08
H4 3.022775e-01
H5 1.214983e-02
H6 5.912065e-04
H7 1.301966e-04
H8 1.000000e+00

In [60]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wV.csv') #Replace here
uci_location <- read.csv('c_result/hub_wV.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       23.766 5      4.567073e-04 5        0      0
2 H2        8.158 7      1.516766e-06 7        0      0
3 H3        5.023 8      7.732146e-08 8        0      0
4 H4    16515.750 2      3.022775e-01 2        0      0
5 H5       55.040 3      1.214983e-02 3        0      0
6 H6       25.148 4      5.912065e-04 4        0      0
7 H7       18.307 6      1.301966e-04 6        0      0
8 H8    54632.867 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          27.615  9     1.691667e-04 10        1     1
9  L2       27990.016  3     4.778698e-01  3        0     0
10 L3           5.023 16     7.128886e-09 16        0     0
11 L4          58.632  7     6.592830e-03  7        0     0
12 L5           9.058 14     7.043182e-05 12       -2     4
13 L6          19.011 11     3.602484e-05 13        2     4
14 L7       58580.098  1     1.000000e+00  1        0     0
15 L8        6286.072  5     1.072079e-01  5        0     0
16 L9          63.515  6     7.141878e-03  6        0     0
2  L10         30.006  8     2.333092e-04  9        1     1
3  L11          8.158 15     2.139439e-07 15        0     0
4  L12      12016.473  4     2.049389e-01  4        0     0
5  L13         17.791 12     1.089866e-04 11       -1     1
6  L14         17.545 13     3.324640e-05 14        1     1
7  L15         24.608 10     2.767069e-03  8       -2     4
8  L16      53336.332  2     9.106040e-01  2        0     0

[1] "Sum of d Rank^2: 16"
[1] "P: 0.976556776556777"

7. As

In [61]:
new_normHumParameters <- normHumParameters
new_normHumParameters$As <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wAs.csv")
write.csv(Hub, "hub_wAs.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  6.606090e-04
L2  4.597954e-01
L3  3.756319e-08
L4  1.712549e-03
L5  3.564355e-04
L6  1.192922e-04
L7  1.000000e+00
L8  1.109152e-01
L9  2.235701e-03
L10 7.522982e-04
L11 8.339500e-06
L12 1.542006e-01
L13 3.362140e-04
L14 1.325289e-04
L15 9.925897e-04
L16 8.761625e-01

   [,1]
H1 5.936923e-04
H2 8.982473e-06
H3 4.045931e-08
H4 3.247927e-01
H5 1.943773e-03
H6 6.732265e-04
H7 1.359929e-04
H8 1.000000e+00

In [62]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wAs.csv') #Replace here
uci_location <- read.csv('c_result/hub_wAs.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       19.850 5      5.936923e-04 5        0      0
2 H2        8.133 7      8.982473e-06 7        0      0
3 H3        2.995 8      4.045931e-08 8        0      0
4 H4    18142.770 2      3.247927e-01 2        0      0
5 H5       26.669 3      1.943773e-03 3        0      0
6 H6       20.455 4      6.732265e-04 4        0      0
7 H7       14.210 6      1.359929e-04 6        0      0
8 H8    55848.117 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          23.790  9     6.606090e-04 10        1     1
9  L2       27658.357  3     4.597954e-01  3        0     0
10 L3           2.995 16     3.756319e-08 16        0     0
11 L4          25.308  7     1.712549e-03  7        0     0
12 L5          11.665 14     3.564355e-04 11       -3     9
13 L6          13.426 12     1.192922e-04 14        2     4
14 L7       60157.145  1     1.000000e+00  1        0     0
15 L8        6674.454  5     1.109152e-01  5        0     0
16 L9          33.039  6     2.235701e-03  6        0     0
2  L10         24.619  8     7.522982e-04  9        1     1
3  L11          8.133 15     8.339500e-06 15        0     0
4  L12       9279.204  4     1.542006e-01  4        0     0
5  L13         12.108 13     3.362140e-04 12       -1     1
6  L14         14.916 10     1.325289e-04 13        3     9
7  L15         14.668 11     9.925897e-04  8       -3     9
8  L16      52704.340  2     8.761625e-01  2        0     0

[1] "Sum of d Rank^2: 34"
[1] "P: 0.95018315018315"

8. p

In [63]:
new_normHumParameters <- normHumParameters
new_normHumParameters$P <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wP.csv")
write.csv(Hub, "hub_wP.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  6.510294e-04
L2  6.050203e-01
L3  1.600374e-06
L4  2.430897e-03
L5  8.772324e-05
L6  1.490677e-03
L7  9.061854e-01
L8  7.508206e-02
L9  2.298045e-03
L10 1.851500e-04
L11 7.003148e-05
L12 1.043833e-01
L13 5.075199e-04
L14 1.608185e-03
L15 1.020269e-03
L16 1.000000e+00

   [,1]
H1 6.143127e-04
H2 7.314509e-05
H3 1.671527e-06
H4 2.317877e-01
H5 2.222048e-03
H6 1.606686e-04
H7 1.620646e-03
H8 1.000000e+00

In [64]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wP.csv') #Replace here
uci_location <- read.csv('c_result/hub_wP.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       25.365 5      6.143127e-04 5        0      0
2 H2       15.781 7      7.314509e-05 7        0      0
3 H3        7.479 8      1.671527e-06 8        0      0
4 H4    16108.112 2      2.317877e-01 2        0      0
5 H5       34.992 3      2.222048e-03 3        0      0
6 H6       18.688 6      1.606686e-04 6        0      0
7 H7       32.227 4      1.620646e-03 4        0      0
8 H8    69459.094 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          28.076 10     6.510294e-04 11        1     1
9  L2       43891.117  3     6.050203e-01  3        0     0
10 L3           7.479 16     1.600374e-06 16        0     0
11 L4          39.982  6     2.430897e-03  6        0     0
12 L5          10.657 15     8.772324e-05 14       -1     1
13 L6          30.961  9     1.490677e-03  9        0     0
14 L7       65746.844  2     9.061854e-01  2        0     0
15 L8        5452.312  5     7.508206e-02  5        0     0
16 L9          37.797  7     2.298045e-03  7        0     0
2  L10         22.493 11     1.851500e-04 13        2     4
3  L11         15.781 14     7.003148e-05 15        1     1
4  L12       7580.112  4     1.043833e-01  4        0     0
5  L13         21.887 12     5.075199e-04 12        0     0
6  L14         33.401  8     1.608185e-03  8        0     0
7  L15         16.781 13     1.020269e-03 10       -3     9
8  L16      72544.867  1     1.000000e+00  1        0     0

[1] "Sum of d Rank^2: 16"
[1] "P: 0.976556776556777"

### Leave-multiple-out
1. Fl and Dp

In [65]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normHumParameters <- normHumParameters
#new_normHumParameters$P <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO1.csv")
write.csv(Hub, "hub_wLMO1.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  9.370142e-03
L2  6.792634e-01
L3  2.279186e-07
L4  9.556763e-03
L5  1.091664e-03
L6  7.664123e-04
L7  1.000000e+00
L8  9.349242e-02
L9  1.031955e-02
L10 2.912591e-03
L11 3.514597e-05
L12 1.787204e-01
L13 5.748877e-03
L14 7.236530e-04
L15 4.011058e-03
L16 7.435881e-01

   [,1]
H1 5.028798e-03
H2 1.122055e-05
H3 3.876202e-08
H4 2.570089e-01
H5 5.714556e-03
H6 1.308942e-03
H7 3.487415e-04
H8 1.000000e+00

In [66]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO1.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO1.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       56.514 4      5.028798e-03 4        0      0
2 H2       17.487 7      1.122055e-05 7        0      0
3 H3        7.842 8      3.876202e-08 8        0      0
4 H4    13180.856 2      2.570089e-01 2        0      0
5 H5       58.408 3      5.714556e-03 3        0      0
6 H6       41.223 5      1.308942e-03 5        0      0
7 H7       31.508 6      3.487415e-04 6        0      0
8 H8    51228.797 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          66.249  6     9.370142e-03  8        2     4
8  L2       38701.992  2     6.792634e-01  3        1     1
9  L3           7.842 15     2.279186e-07 16        1     1
10 L4          62.332  7     9.556763e-03  7        0     0
11 L5          18.626 13     1.091664e-03 12       -1     1
12 L6          32.385 10     7.664123e-04 13        3     9
13 L7       56982.531  1     1.000000e+00  1        0     0
14 L8        5333.465  4     9.349242e-02  5        1     1
15 L9          67.308  5     1.031955e-02  6        1     1
2  L10         49.693  8     2.912591e-03 11        3     9
3  L11         17.487 14     3.514597e-05 15        1     1
4  L12      10195.467  3     1.787204e-01  4        1     1
5  L13         40.646  9     5.748877e-03  9        0     0
6  L14         30.579 11     7.236530e-04 14        3     9
7  L15         26.161 12     4.011058e-03 10       -2     4

[1] "Sum of d Rank^2: 42"
[1] "P: 0.925311203319502"

2. Fl, Dp, Sl

In [67]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
#new_normHumParameters$P <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO2.csv")
write.csv(Hub, "hub_wLMO2.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  1.227316e-02
L2  6.763325e-01
L3  8.552762e-09
L4  3.585894e-03
L5  4.682646e-04
L6  3.594566e-04
L7  1.000000e+00
L8  5.022298e-02
L9  3.842086e-03
L10 1.703765e-03
L11 9.721473e-06
L12 1.081712e-01
L13 6.984885e-03
L14 3.407226e-04
L15 6.830464e-04
L16 7.026941e-01

   [,1]
H1 1.172052e-02
H2 1.100334e-05
H3 9.680522e-09
H4 1.759297e-01
H5 3.919395e-03
H6 1.626941e-03
H7 3.965358e-04
H8 1.000000e+00

In [68]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO2.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO2.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       47.143 3      1.172052e-02 3        0      0
2 H2       11.595 7      1.100334e-05 7        0      0
3 H3        4.362 8      9.680522e-09 8        0      0
4 H4     5836.647 2      1.759297e-01 2        0      0
5 H5       35.201 4      3.919395e-03 4        0      0
6 H6       28.692 5      1.626941e-03 5        0      0
7 H7       21.453 6      3.965358e-04 6        0      0
8 H8    33130.629 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          55.876  6     1.227316e-02  6        0      0
9  L2       25361.631  3     6.763325e-01  3        0      0
10 L3           4.362 16     8.552762e-09 16        0      0
11 L4          36.452  8     3.585894e-03  9        1      1
12 L5           9.347 14     4.682646e-04 12       -2      4
13 L6          22.011 11     3.594566e-04 13        2      4
14 L7       37502.574  1     1.000000e+00  1        0      0
15 L8        1887.575  5     5.022298e-02  5        0      0
16 L9          39.056  7     3.842086e-03  8        1      1
2  L10         34.008  9     1.703765e-03 10        1      1
3  L11         11.595 13     9.721473e-06 15        2      4
4  L12       4065.495  4     1.081712e-01  4        0      0
5  L13         31.800 10     6.984885e-03  7       -3      9
6  L14         20.864 12     3.407226e-04 14        2      4
7  L15          6.943 15     6.830464e-04 11       -4     16
8  L16      26350.158  2     7.026941e-01  2        0      0

[1] "Sum of d Rank^2: 44"
[1] "P: 0.935531135531136"

3. Fl, Dp, Sl, Fh

In [69]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO3.csv")
write.csv(Hub, "hub_wLMO3.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  2.143377e-02
L2  7.265774e-01
L3  8.308664e-10
L4  3.197001e-04
L5  1.474845e-05
L6  5.575255e-05
L7  1.000000e+00
L8  2.117689e-02
L9  4.605280e-04
L10 5.765683e-05
L11 5.467177e-07
L12 8.646990e-02
L13 1.138002e-02
L14 6.053012e-05
L15 3.806207e-05
L16 7.585282e-01

   [,1]
H1 1.980224e-02
H2 6.032315e-07
H3 9.167524e-10
H4 1.326109e-01
H5 4.257426e-04
H6 5.397317e-05
H7 6.425965e-05
H8 1.000000e+00

In [70]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO3.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO3.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       46.232 3      1.980224e-02 3        0      0
2 H2        6.845 7      6.032315e-07 7        0      0
3 H3        3.106 8      9.167524e-10 8        0      0
4 H4     3181.618 2      1.326109e-01 2        0      0
5 H5       18.696 4      4.257426e-04 4        0      0
6 H6       13.088 6      5.397317e-05 6        0      0
7 H7       13.462 5      6.425965e-05 5        0      0
8 H8    23951.053 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          55.214  6     2.143377e-02  5       -1     1
9  L2       19201.260  3     7.265774e-01  3        0     0
10 L3           3.106 15     8.308664e-10 16        1     1
11 L4          15.491  9     3.197001e-04  9        0     0
12 L5           3.946 14     1.474845e-05 14        0     0
13 L6          12.887 12     5.575255e-05 12        0     0
14 L7       26429.020  1     1.000000e+00  1        0     0
15 L8         561.141  5     2.117689e-02  6        1     1
16 L9          22.315  8     4.605280e-04  8        0     0
2  L10         15.426 10     5.765683e-05 11        1     1
3  L11          6.845 13     5.467177e-07 15        2     4
4  L12       2291.260  4     8.646990e-02  4        0     0
5  L13         29.315  7     1.138002e-02  7        0     0
6  L14         13.992 11     6.053012e-05 10       -1     1
7  L15          1.844 16     3.806207e-05 13       -3     9
8  L16      20045.623  2     7.585282e-01  2        0     0

[1] "Sum of d Rank^2: 18"
[1] "P: 0.973626373626374"

4. Fl, Dp, Sl, Fh, Du

In [71]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
new_normHumParameters$Du <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO4.csv")
write.csv(Hub, "hub_wLMO4.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  2.080634e-02
L2  6.540153e-01
L3  8.877372e-09
L4  1.604774e-04
L5  2.871044e-05
L6  7.342453e-05
L7  1.000000e+00
L8  0.000000e+00
L9  4.011935e-04
L10 1.435522e-04
L11 1.574641e-06
L12 7.590807e-02
L13 1.040317e-02
L14 9.789938e-05
L15 0.000000e+00
L16 6.540153e-01

   [,1]
H1 1.321021e-02
H2 4.265642e-07
H3 1.352725e-09
H4 1.160628e-01
H5 1.632167e-04
H6 5.476688e-05
H7 3.699854e-05
H8 1.000000e+00

In [72]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO4.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO4.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       26.367 3      1.321021e-02 3        0      0
2 H2        4.222 7      4.265642e-07 7        0      0
3 H3        2.097 8      1.352725e-09 8        0      0
4 H4     1781.756 2      1.160628e-01 2        0      0
5 H5       10.155 4      1.632167e-04 4        0      0
6 H6        8.466 5      5.476688e-05 5        0      0
7 H7        7.954 6      3.699854e-05 6        0      0
8 H8    15318.763 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          31.641  5     2.080634e-02  5        0     0
9  L2       11652.775  3     6.540153e-01  3        0     0
10 L3           2.097 13     8.877372e-09 14        1     1
11 L4           4.903 11     1.604774e-04  8       -3     9
12 L5           1.954 14     2.871044e-05 12       -2     4
13 L6           6.682 10     7.342453e-05 11        1     1
14 L7       17818.172  1     1.000000e+00  1        0     0
15 L8           0.000 16     0.000000e+00 16        0     0
16 L9          12.256  7     4.011935e-04  7        0     0
2  L10          9.768  8     1.435522e-04  9        1     1
3  L11          4.222 12     1.574641e-06 13        1     1
4  L12       1356.031  4     7.590807e-02  4        0     0
5  L13         15.820  6     1.040317e-02  6        0     0
6  L14          8.909  9     9.789938e-05 10        1     1
7  L15          0.000 15     0.000000e+00 15        0     0
8  L16      11652.775  2     6.540153e-01  2        0     0

[1] "Sum of d Rank^2: 18"
[1] "P: 0.973626373626374"

5. Fl, Dp, Sl, Fh, Du, V

In [73]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
new_normHumParameters$Du <- generateEmpty(16,8)
new_normHumParameters$V <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO5.csv")
write.csv(Hub, "hub_wLMO5.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  3.380493e-02
L2  5.000000e-01
L3  7.384800e-15
L4  1.690247e-02
L5  0.000000e+00
L6  1.935881e-09
L7  1.000000e+00
L8  0.000000e+00
L9  3.380493e-02
L10 5.074796e-04
L11 7.384800e-15
L12 5.074796e-04
L13 1.690247e-02
L14 1.935881e-09
L15 0.000000e+00
L16 5.000000e-01

   [,1]
H1 3.130086e-02
H2 1.641067e-15
H3 1.641067e-15
H4 4.510930e-04
H5 3.130086e-02
H6 4.510930e-04
H7 8.603916e-10
H8 1.000000e+00

In [74]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO5.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO5.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb   rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1    24.179 2      3.130086e-02 3        1      1
2 H2     0.972 7      1.641067e-15 8        1      1
3 H3     0.972 6      1.641067e-15 7        1      1
4 H4     9.701 4      4.510930e-04 5        1      1
5 H5    24.179 1      3.130086e-02 2        1      1
6 H6     9.701 3      4.510930e-04 4        1      1
7 H7     2.429 5      8.603916e-10 6        1      1

[1] "Sum of d Rank^2: 7"
[1] "P: 0.87719298245614"

   Location MHRb     rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1         29.015  5     3.380493e-02  5       0      0
9  L2       3240.010  3     5.000000e-01  3       0      0
10 L3          0.972 13     7.384800e-15 13       0      0
11 L4         14.507  7     1.690247e-02  7       0      0
12 L5          0.000 16     0.000000e+00 16       0      0
13 L6          2.429 11     1.935881e-09 11       0      0
14 L7       6480.019  1     1.000000e+00  1       0      0
15 L8          0.000 15     0.000000e+00 15       0      0
16 L9         29.015  4     3.380493e-02  4       0      0
2  L10         9.701  9     5.074796e-04  9       0      0
3  L11         0.972 12     7.384800e-15 12       0      0
4  L12         9.701  8     5.074796e-04  8       0      0
5  L13        14.507  6     1.690247e-02  6       0      0
6  L14         2.429 10     1.935881e-09 10       0      0
7  L15         0.000 14     0.000000e+00 14       0      0
8  L16      3240.010  2     5.000000e-01  2       0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

6. Fl, Dp, Sl, Fh, Du, V, As

In [75]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
new_normHumParameters$Du <- generateEmpty(16,8)
new_normHumParameters$V <- generateEmpty(16,8)
new_normHumParameters$As <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO6.csv")
write.csv(Hub, "hub_wLMO6.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  1
L2  0
L3  0
L4  0
L5  0
L6  0
L7  1
L8  0
L9  1
L10 1
L11 0
L12 1
L13 0
L14 0
L15 0
L16 0

   [,1]
H1 1
H2 0
H3 0
H4 1
H5 1
H6 1
H7 0
H8 1

In [76]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO6.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO6.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb rank_b MHRbmc rank_bmc d Rank d Rank^2
1 H1    810  5      1      5        0      0
2 H2      0  8      0      8        0      0
3 H3      0  7      0      7        0      0
4 H4    810  4      1      4        0      0
5 H5    810  3      1      3        0      0
6 H6    810  2      1      2        0      0
7 H7      0  6      0      6        0      0
8 H8    810  1      1      1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb rank_b MHRbmc rank_bmc d Rank d Rank^2
1  L1       810   5     1       5       0      0
9  L2         0  16     0      16       0      0
10 L3         0  15     0      15       0      0
11 L4         0  14     0      14       0      0
12 L5         0  13     0      13       0      0
13 L6         0  12     0      12       0      0
14 L7       810   4     1       4       0      0
15 L8         0  11     0      11       0      0
16 L9       810   3     1       3       0      0
2  L10      810   2     1       2       0      0
3  L11        0  10     0      10       0      0
4  L12      810   1     1       1       0      0
5  L13        0   9     0       9       0      0
6  L14        0   8     0       8       0      0
7  L15        0   7     0       7       0      0
8  L16        0   6     0       6       0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

7. Fl, Dp, Sl, Fh, Du, V, P

In [77]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Dp <- rep(0, length(new_normLocParameters$Dp))
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
new_normHumParameters$Du <- generateEmpty(16,8)
new_normHumParameters$V <- generateEmpty(16,8)
new_normHumParameters$P <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO7.csv")
write.csv(Hub, "hub_wLMO7.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  1.156102e-02
L2  1.000000e+00
L3  5.645029e-06
L4  1.156102e-02
L5  0.000000e+00
L6  1.156102e-02
L7  1.000000e+00
L8  0.000000e+00
L9  1.156102e-02
L10 5.645029e-06
L11 5.645029e-06
L12 5.645029e-06
L13 1.156102e-02
L14 1.156102e-02
L15 0.000000e+00
L16 1.000000e+00

   [,1]
H1 7.707347e-03
H2 1.881676e-06
H3 1.881676e-06
H4 1.881676e-06
H5 7.707347e-03
H6 1.881676e-06
H7 7.707347e-03
H8 1.000000e+00

In [78]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO7.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO7.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb     rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       4.850 4      7.707347e-03 4        0      0
2 H2       1.214 8      1.881676e-06 8        0      0
3 H3       1.214 7      1.881676e-06 7        0      0
4 H4       1.214 6      1.881676e-06 6        0      0
5 H5       4.850 3      7.707347e-03 3        0      0
6 H6       1.214 5      1.881676e-06 5        0      0
7 H7       4.850 2      7.707347e-03 2        0      0
8 H8    2430.000 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb     rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          4.850  9     1.156102e-02  9       0      0
9  L2       2430.031  3     1.000000e+00  3       0      0
10 L3          1.214 13     5.645029e-06 13       0      0
11 L4          4.850  8     1.156102e-02  8       0      0
12 L5          0.000 16     0.000000e+00 16       0      0
13 L6          4.850  7     1.156102e-02  7       0      0
14 L7       2430.031  2     1.000000e+00  2       0      0
15 L8          0.000 15     0.000000e+00 15       0      0
16 L9          4.850  6     1.156102e-02  6       0      0
2  L10         1.214 12     5.645029e-06 12       0      0
3  L11         1.214 11     5.645029e-06 11       0      0
4  L12         1.214 10     5.645029e-06 10       0      0
5  L13         4.850  5     1.156102e-02  5       0      0
6  L14         4.850  4     1.156102e-02  4       0      0
7  L15         0.000 14     0.000000e+00 14       0      0
8  L16      2430.031  1     1.000000e+00  1       0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

8. Sl, Du

In [79]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Du <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO8.csv")
write.csv(Hub, "hub_wLMO8.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  2.659994e-03
L2  4.702497e-01
L3  1.510306e-06
L4  2.194956e-03
L5  3.569646e-04
L6  9.319503e-04
L7  1.000000e+00
L8  2.849619e-02
L9  3.672039e-03
L10 1.499251e-03
L11 6.402328e-05
L12 9.973667e-02
L13 1.462997e-03
L14 1.203602e-03
L15 3.658260e-04
L16 8.733208e-01

   [,1]
H1 2.388245e-03
H2 6.840536e-05
H3 1.613679e-06
H4 2.120377e-01
H5 3.160263e-03
H6 1.367162e-03
H7 1.159320e-03
H8 1.000000e+00

In [80]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO8.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO8.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       16.932 4      2.388245e-03 4        0      0
2 H2        6.786 7      6.840536e-05 7        0      0
3 H3        2.932 8      1.613679e-06 8        0      0
4 H4     9364.062 2      2.120377e-01 2        0      0
5 H5       18.378 3      3.160263e-03 3        0      0
6 H6       14.466 5      1.367162e-03 5        0      0
7 H7       13.826 6      1.159320e-03 6        0      0
8 H8    44148.875 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          20.149  7     2.659994e-03  7        0     0
9  L2       22182.012  3     4.702497e-01  3        0     0
10 L3           2.932 15     1.510306e-06 16        1     1
11 L4          13.638 10     2.194956e-03  8       -2     4
12 L5           4.035 14     3.569646e-04 14        0     0
13 L6          11.875 11     9.319503e-04 12        1     1
14 L7       47172.777  1     1.000000e+00  1        0     0
15 L8        1344.968  5     2.849619e-02  5        0     0
16 L9          22.815  6     3.672039e-03  6        0     0
2  L10         16.949  8     1.499251e-03  9        1     1
3  L11          6.786 13     6.402328e-05 15        2     4
4  L12       4707.390  4     9.973667e-02  4        0     0
5  L13         11.082 12     1.462997e-03 10       -2     4
6  L14         15.337  9     1.203602e-03 11        2     4
7  L15          2.273 16     3.658260e-04 13       -3     9
8  L16      41195.164  2     8.733208e-01  2        0     0

[1] "Sum of d Rank^2: 28"
[1] "P: 0.958974358974359"

9. Sl, Fh

In [81]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO9.csv")
write.csv(Hub, "hub_wLMO9.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  2.454257e-03
L2  5.515096e-01
L3  8.168411e-08
L4  5.947616e-04
L5  1.792183e-05
L6  2.001738e-04
L7  9.983051e-01
L8  2.199916e-02
L9  1.009178e-03
L10 7.006268e-05
L11 4.009376e-06
L12 8.982739e-02
L13 1.303060e-03
L14 2.602773e-04
L15 7.080968e-05
L16 1.000000e+00

   [,1]
H1 2.070740e-03
H2 4.040056e-06
H3 8.230916e-08
H4 1.814831e-01
H5 8.286222e-04
H6 5.989681e-05
H7 2.359400e-04
H8 1.000000e+00

In [82]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO9.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO9.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       23.131 3      2.070740e-03 3        0      0
2 H2        5.963 7      4.040056e-06 7        0      0
3 H3        2.911 8      8.230916e-08 8        0      0
4 H4     8359.780 2      1.814831e-01 2        0      0
5 H5       18.364 4      8.286222e-04 4        0      0
6 H6       10.203 6      5.989681e-05 6        0      0
7 H7       13.714 5      2.359400e-04 5        0      0
8 H8    46034.289 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb      rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          27.625  6     2.454257e-03  6        0      0
9  L2       25582.352  3     5.515096e-01  3        0      0
10 L3           2.911 15     8.168411e-08 16        1      1
11 L4          13.282 10     5.947616e-04  9       -1      1
12 L5           3.076 14     1.792183e-05 14        0      0
13 L6          11.724 12     2.001738e-04 11       -1      1
14 L7       46311.180  2     9.983051e-01  2        0      0
15 L8        1021.717  5     2.199916e-02  5        0      0
16 L9          22.536  7     1.009178e-03  8        1      1
2  L10         12.026 11     7.006268e-05 13        2      4
3  L11          5.963 13     4.009376e-06 15        2      4
4  L12       4171.896  4     8.982739e-02  4        0      0
5  L13         14.667  9     1.303060e-03  7       -2      4
6  L14         15.244  8     2.602773e-04 10        2      4
7  L15          1.581 16     7.080968e-05 12       -4     16
8  L16      46386.055  1     1.000000e+00  1        0      0

[1] "Sum of d Rank^2: 36"
[1] "P: 0.947252747252747"

10. Fl, Sl, Fh, Du, V, As, P

In [83]:
new_normLocParameters <- normLocParameters
new_normLocParameters$Fl <- rep(0, length(new_normLocParameters$Fl))
new_normLocParameters$Sl <- rep(0, length(new_normLocParameters$Sl))
new_normHumParameters <- normHumParameters
new_normHumParameters$Fh <- generateEmpty(16,8)
new_normHumParameters$Du <- generateEmpty(16,8)
new_normHumParameters$V <- generateEmpty(16,8)
new_normHumParameters$As <- generateEmpty(16,8)
new_normHumParameters$P <- generateEmpty(16,8)
linkWeight <- generateLinkWeight(new_normLocParameters, new_normHumParameters, lnkMtrxH)
Hub = as.matrix(linkWeight) %*% t(linkWeight)
#Hub
Authority = t(linkWeight)%*%as.matrix(linkWeight)
#Authority

write.csv(Authority, "authority_wLMO10.csv")
write.csv(Hub, "hub_wLMO10.csv")

k = 1000
auth <- c(rep(1,nrow(Authority))) 
hub <- c(rep(1,nrow(Hub))) 
ip <- powerMethod(Hub,hub,10^-2,k)
ih <- powerMethod(Authority,auth,10^-2,k)
vp <- ip$vector/max(ip$vector) 
vh <- ih$vector/max(ih$vector)
vp
vh

    [,1]
L1  0.000000e+00
L2  0.000000e+00
L3  0.000000e+00
L4  0.000000e+00
L5  0.000000e+00
L6  0.000000e+00
L7  4.968392e-01
L8  0.000000e+00
L9  1.541669e-04
L10 0.000000e+00
L11 0.000000e+00
L12 0.000000e+00
L13 0.000000e+00
L14 4.633911e-05
L15 0.000000e+00
L16 1.000000e+00

   [,1]
H1 0.000000e+00
H2 0.000000e+00
H3 0.000000e+00
H4 1.746911e-01
H5 1.624748e-04
H6 0.000000e+00
H7 4.883628e-05
H8 1.000000e+00

In [84]:
humanRank <- as.data.frame(vh[order(vh, decreasing = TRUE),])
locationRank <- as.data.frame(vp[order(vp, decreasing = TRUE),])
humanRank$Human <- row.names(humanRank)
row.names(humanRank)<-NULL
locationRank$Location <- row.names(locationRank)
row.names(locationRank)<-NULL
names(humanRank) <- c('MHRbmc', 'Human')
names(locationRank) <- c('MHRbmc', 'Location')

#Human BMC
humanRank$rank_bmc <- NA
order.MHRb<-order(humanRank$MHRb)
humanRank$rank_bmc[order.MHRb] <- nrow(humanRank):1
#humanRank

#Location BMC
locationRank$rank_bmc <- NA
order.MHRb<-order(locationRank$MHRb)
locationRank$rank_bmc[order.MHRb] <- nrow(locationRank):1
#locationRank

####
uci_human <- read.csv('c_result/authority_wLMO10.csv') #Replace here
uci_location <- read.csv('c_result/hub_wLMO10.csv') # Replace here
names(uci_human)<-c("Human", "MHRb")
names(uci_location)<-c("Location", "MHRb")

#Human UCI
uci_human$rank_b <- NA
order.MHRb<-order(uci_human$MHRb)
uci_human$rank_b[order.MHRb] <- nrow(uci_human):1
#uci_human

#Location UCI
uci_location$rank_b <- NA
order.MHRb<-order(uci_location$MHRb)
uci_location$rank_b[order.MHRb] <- nrow(uci_location):1
#uci_location

human_compare_2 <- merge(uci_human, humanRank, by='Human')
location_compare_2 <- merge(uci_location, locationRank, by='Location')
human_compare_2$`d Rank` <- human_compare_2$rank_bmc - human_compare_2$rank_b
location_compare_2$`d Rank` <- location_compare_2$rank_bmc - location_compare_2$rank_b
human_compare_2$`d Rank^2` <- (human_compare_2$`d Rank`)^2
location_compare_2$`d Rank^2` <- (location_compare_2$`d Rank`)^2
human_compare_2
print(paste("Sum of d Rank^2:",sum(human_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(human_compare_2$`d Rank^2`))/(nrow(human_compare_2)*nrow(human_compare_2)**2-1))  ))
location_compare_2[order(as.numeric(gsub("L","", location_compare_2$Location))),]
print(paste("Sum of d Rank^2:",sum(location_compare_2$`d Rank^2`)))
print(paste("P:",1-((6*sum(location_compare_2$`d Rank^2`))/(nrow(location_compare_2)*nrow(location_compare_2)**2-1))  ))

  Human MHRb     rank_b MHRbmc       rank_bmc d Rank d Rank^2
1 H1       0.000 8      0.000000e+00 8        0      0
2 H2       0.000 7      0.000000e+00 7        0      0
3 H3       0.000 6      0.000000e+00 6        0      0
4 H4     193.625 2      1.746911e-01 2        0      0
5 H5       0.059 3      1.624748e-04 3        0      0
6 H6       0.000 5      0.000000e+00 5        0      0
7 H7       0.039 4      4.883628e-05 4        0      0
8 H8    1116.190 1      1.000000e+00 1        0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"

   Location MHRb     rank_b MHRbmc       rank_bmc d Rank d Rank^2
1  L1          0.000 16     0.000000e+00 16       0      0
9  L2          0.000 15     0.000000e+00 15       0      0
10 L3          0.000 14     0.000000e+00 14       0      0
11 L4          0.000 13     0.000000e+00 13       0      0
12 L5          0.000 12     0.000000e+00 12       0      0
13 L6          0.000 11     0.000000e+00 11       0      0
14 L7        583.659  2     4.968392e-01  2       0      0
15 L8          0.000 10     0.000000e+00 10       0      0
16 L9          0.059  3     1.541669e-04  3       0      0
2  L10         0.000  9     0.000000e+00  9       0      0
3  L11         0.000  8     0.000000e+00  8       0      0
4  L12         0.000  7     0.000000e+00  7       0      0
5  L13         0.000  6     0.000000e+00  6       0      0
6  L14         0.039  4     4.633911e-05  4       0      0
7  L15         0.000  5     0.000000e+00  5       0      0
8  L16      1176.418  1     1.000000e+00  1       0      0

[1] "Sum of d Rank^2: 0"
[1] "P: 1"